/********************************************************************
* EmathDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error EmathDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern G__DLLEXPORT int G__cpp_dllrevEmathDict();
extern G__DLLEXPORT void G__set_cpp_environmentEmathDict();
extern G__DLLEXPORT void G__cpp_setup_tagtableEmathDict();
extern G__DLLEXPORT void G__cpp_setup_inheritanceEmathDict();
extern G__DLLEXPORT void G__cpp_setup_typetableEmathDict();
extern G__DLLEXPORT void G__cpp_setup_memvarEmathDict();
extern G__DLLEXPORT void G__cpp_setup_globalEmathDict();
extern G__DLLEXPORT void G__cpp_setup_memfuncEmathDict();
extern G__DLLEXPORT void G__cpp_setup_funcEmathDict();
extern G__DLLEXPORT void G__cpp_setupEmathDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TIndexCell.h"
#include "EdbMath.h"
#include "EdbCell2.h"
#include "EdbCell1.h"
#include "EdbMask.h"
#include "EdbCombGen.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EmathDictLN_TClass;
extern G__linked_taginfo G__EmathDictLN_TBuffer;
extern G__linked_taginfo G__EmathDictLN_TMemberInspector;
extern G__linked_taginfo G__EmathDictLN_TObject;
extern G__linked_taginfo G__EmathDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR;
extern G__linked_taginfo G__EmathDictLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__EmathDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EmathDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EmathDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__EmathDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__EmathDictLN_TObjArray;
extern G__linked_taginfo G__EmathDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EmathDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EmathDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR;
extern G__linked_taginfo G__EmathDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__EmathDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__EmathDictLN_TIndexCell;
extern G__linked_taginfo G__EmathDictLN_TIndexCellIter;
extern G__linked_taginfo G__EmathDictLN_TIndexCellIterV;
extern G__linked_taginfo G__EmathDictLN_TArray;
extern G__linked_taginfo G__EmathDictLN_TArrayI;
extern G__linked_taginfo G__EmathDictLN_TArrayD;
extern G__linked_taginfo G__EmathDictLN_TArrayC;
extern G__linked_taginfo G__EmathDictLN_TArrayF;
extern G__linked_taginfo G__EmathDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__EmathDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__EmathDictLN_TH1I;
extern G__linked_taginfo G__EmathDictLN_TH1F;
extern G__linked_taginfo G__EmathDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__EmathDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__EmathDictLN_TH2F;
extern G__linked_taginfo G__EmathDictLN_TH2D;
extern G__linked_taginfo G__EmathDictLN_EdbMath;
extern G__linked_taginfo G__EmathDictLN_TIndex2;
extern G__linked_taginfo G__EmathDictLN_EdbFilter2D;
extern G__linked_taginfo G__EmathDictLN_EdbH1;
extern G__linked_taginfo G__EmathDictLN_EdbCell1;
extern G__linked_taginfo G__EmathDictLN_EdbH2;
extern G__linked_taginfo G__EmathDictLN_EdbPeak2;
extern G__linked_taginfo G__EmathDictLN_EdbCell2;
extern G__linked_taginfo G__EmathDictLN_EdbMask;
extern G__linked_taginfo G__EmathDictLN_EdbCombGen;

/* STUB derived class for protected member access */
