/********************************************************************
* bmatrixDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error bmatrixDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern G__DLLEXPORT int G__cpp_dllrevbmatrixDict();
extern G__DLLEXPORT void G__set_cpp_environmentbmatrixDict();
extern G__DLLEXPORT void G__cpp_setup_tagtablebmatrixDict();
extern G__DLLEXPORT void G__cpp_setup_inheritancebmatrixDict();
extern G__DLLEXPORT void G__cpp_setup_typetablebmatrixDict();
extern G__DLLEXPORT void G__cpp_setup_memvarbmatrixDict();
extern G__DLLEXPORT void G__cpp_setup_globalbmatrixDict();
extern G__DLLEXPORT void G__cpp_setup_memfuncbmatrixDict();
extern G__DLLEXPORT void G__cpp_setup_funcbmatrixDict();
extern G__DLLEXPORT void G__cpp_setupbmatrixDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "bitmatrix.h"
#include "basematrix.h"
#include "bytematrix.h"
#include "bitview.h"
#include "deriv.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__bmatrixDictLN_TClass;
extern G__linked_taginfo G__bmatrixDictLN_TBuffer;
extern G__linked_taginfo G__bmatrixDictLN_TMemberInspector;
extern G__linked_taginfo G__bmatrixDictLN_TObject;
extern G__linked_taginfo G__bmatrixDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR;
extern G__linked_taginfo G__bmatrixDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__bmatrixDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__bmatrixDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__bmatrixDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__bmatrixDictLN_TObjArray;
extern G__linked_taginfo G__bmatrixDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__bmatrixDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__bmatrixDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR;
extern G__linked_taginfo G__bmatrixDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__bmatrixDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__bmatrixDictLN_TBaseMatrix;
extern G__linked_taginfo G__bmatrixDictLN_TBitMatrix;
extern G__linked_taginfo G__bmatrixDictLN_TByteMatrix;
extern G__linked_taginfo G__bmatrixDictLN_TH2F;
extern G__linked_taginfo G__bmatrixDictLN_EdbFrame;
extern G__linked_taginfo G__bmatrixDictLN_EdbView;
extern G__linked_taginfo G__bmatrixDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__bmatrixDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__bmatrixDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__bmatrixDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__bmatrixDictLN_TBitView;
extern G__linked_taginfo G__bmatrixDictLN_TBinTracking;
extern G__linked_taginfo G__bmatrixDictLN_Deriv;

/* STUB derived class for protected member access */
