//
// File generated by rootcint at Thu Dec 19 18:19:20 2019

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME EmrCint
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "EmrCint.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void EdbEmrIO_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_EdbEmrIO(void *p = 0);
   static void *newArray_EdbEmrIO(Long_t size, void *p);
   static void delete_EdbEmrIO(void *p);
   static void deleteArray_EdbEmrIO(void *p);
   static void destruct_EdbEmrIO(void *p);
   static void streamer_EdbEmrIO(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::EdbEmrIO*)
   {
      ::EdbEmrIO *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::EdbEmrIO >(0);
      static ::ROOT::TGenericClassInfo 
         instance("EdbEmrIO", ::EdbEmrIO::Class_Version(), "./EdbEmrIO.h", 20,
                  typeid(::EdbEmrIO), ::ROOT::DefineBehavior(ptr, ptr),
                  &::EdbEmrIO::Dictionary, isa_proxy, 0,
                  sizeof(::EdbEmrIO) );
      instance.SetNew(&new_EdbEmrIO);
      instance.SetNewArray(&newArray_EdbEmrIO);
      instance.SetDelete(&delete_EdbEmrIO);
      instance.SetDeleteArray(&deleteArray_EdbEmrIO);
      instance.SetDestructor(&destruct_EdbEmrIO);
      instance.SetStreamerFunc(&streamer_EdbEmrIO);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::EdbEmrIO*)
   {
      return GenerateInitInstanceLocal((::EdbEmrIO*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::EdbEmrIO*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

namespace ROOTDict {
   void EdbEmrFileAccess_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_EdbEmrFileAccess(void *p = 0);
   static void *newArray_EdbEmrFileAccess(Long_t size, void *p);
   static void delete_EdbEmrFileAccess(void *p);
   static void deleteArray_EdbEmrFileAccess(void *p);
   static void destruct_EdbEmrFileAccess(void *p);
   static void streamer_EdbEmrFileAccess(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::EdbEmrFileAccess*)
   {
      ::EdbEmrFileAccess *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::EdbEmrFileAccess >(0);
      static ::ROOT::TGenericClassInfo 
         instance("EdbEmrFileAccess", ::EdbEmrFileAccess::Class_Version(), "./EdbEmrIO.h", 39,
                  typeid(::EdbEmrFileAccess), ::ROOT::DefineBehavior(ptr, ptr),
                  &::EdbEmrFileAccess::Dictionary, isa_proxy, 0,
                  sizeof(::EdbEmrFileAccess) );
      instance.SetNew(&new_EdbEmrFileAccess);
      instance.SetNewArray(&newArray_EdbEmrFileAccess);
      instance.SetDelete(&delete_EdbEmrFileAccess);
      instance.SetDeleteArray(&deleteArray_EdbEmrFileAccess);
      instance.SetDestructor(&destruct_EdbEmrFileAccess);
      instance.SetStreamerFunc(&streamer_EdbEmrFileAccess);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::EdbEmrFileAccess*)
   {
      return GenerateInitInstanceLocal((::EdbEmrFileAccess*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::EdbEmrFileAccess*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr EdbEmrIO::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *EdbEmrIO::Class_Name()
{
   return "EdbEmrIO";
}

//______________________________________________________________________________
const char *EdbEmrIO::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::EdbEmrIO*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int EdbEmrIO::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::EdbEmrIO*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void EdbEmrIO::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::EdbEmrIO*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *EdbEmrIO::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::EdbEmrIO*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
atomic_TClass_ptr EdbEmrFileAccess::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *EdbEmrFileAccess::Class_Name()
{
   return "EdbEmrFileAccess";
}

//______________________________________________________________________________
const char *EdbEmrFileAccess::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::EdbEmrFileAccess*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int EdbEmrFileAccess::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::EdbEmrFileAccess*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void EdbEmrFileAccess::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::EdbEmrFileAccess*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *EdbEmrFileAccess::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::EdbEmrFileAccess*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void EdbEmrIO::Streamer(TBuffer &R__b)
{
   // Stream an object of class EdbEmrIO.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b.CheckByteCount(R__s, R__c, EdbEmrIO::IsA());
   } else {
      R__c = R__b.WriteVersion(EdbEmrIO::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void EdbEmrIO::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class EdbEmrIO.
      TClass *R__cl = ::EdbEmrIO::IsA();
      if (R__cl || R__insp.IsA()) { }
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_EdbEmrIO(void *p) {
      return  p ? new(p) ::EdbEmrIO : new ::EdbEmrIO;
   }
   static void *newArray_EdbEmrIO(Long_t nElements, void *p) {
      return p ? new(p) ::EdbEmrIO[nElements] : new ::EdbEmrIO[nElements];
   }
   // Wrapper around operator delete
   static void delete_EdbEmrIO(void *p) {
      delete ((::EdbEmrIO*)p);
   }
   static void deleteArray_EdbEmrIO(void *p) {
      delete [] ((::EdbEmrIO*)p);
   }
   static void destruct_EdbEmrIO(void *p) {
      typedef ::EdbEmrIO current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_EdbEmrIO(TBuffer &buf, void *obj) {
      ((::EdbEmrIO*)obj)->::EdbEmrIO::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::EdbEmrIO

//______________________________________________________________________________
void EdbEmrFileAccess::Streamer(TBuffer &R__b)
{
   // Stream an object of class EdbEmrFileAccess.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      eSides.Streamer(R__b);
      R__b.CheckByteCount(R__s, R__c, EdbEmrFileAccess::IsA());
   } else {
      R__c = R__b.WriteVersion(EdbEmrFileAccess::IsA(), kTRUE);
      TObject::Streamer(R__b);
      eSides.Streamer(R__b);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void EdbEmrFileAccess::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class EdbEmrFileAccess.
      TClass *R__cl = ::EdbEmrFileAccess::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "eSides", &eSides);
      R__insp.InspectMember(eSides, "eSides.");
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_EdbEmrFileAccess(void *p) {
      return  p ? new(p) ::EdbEmrFileAccess : new ::EdbEmrFileAccess;
   }
   static void *newArray_EdbEmrFileAccess(Long_t nElements, void *p) {
      return p ? new(p) ::EdbEmrFileAccess[nElements] : new ::EdbEmrFileAccess[nElements];
   }
   // Wrapper around operator delete
   static void delete_EdbEmrFileAccess(void *p) {
      delete ((::EdbEmrFileAccess*)p);
   }
   static void deleteArray_EdbEmrFileAccess(void *p) {
      delete [] ((::EdbEmrFileAccess*)p);
   }
   static void destruct_EdbEmrFileAccess(void *p) {
      typedef ::EdbEmrFileAccess current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_EdbEmrFileAccess(TBuffer &buf, void *obj) {
      ((::EdbEmrFileAccess*)obj)->::EdbEmrFileAccess::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::EdbEmrFileAccess

/********************************************************
* EmrCint.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableEmrCint();

extern "C" void G__set_cpp_environmentEmrCint() {
  G__cpp_reset_tagtableEmrCint();
}
#include <new>
extern "C" int G__cpp_dllrevEmrCint() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* EdbEmrIO */
static int G__EmrCint_563_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   EdbEmrIO* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new EdbEmrIO[n];
     } else {
       p = new((void*) gvp) EdbEmrIO[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new EdbEmrIO;
     } else {
       p = new((void*) gvp) EdbEmrIO;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__EmrCintLN_EdbEmrIO));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrCint_563_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdbEmrIO*) G__getstructoffset())->TrackEdb2Emr(*(EdbTrackP*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrCint_563_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdbEmrIO*) G__getstructoffset())->TrackEmr2Edb(*(EdbTrackP*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrCint_563_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdbEmrIO*) G__getstructoffset())->VertexEdb2Emr(*(EdbVertex*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrCint_563_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdbEmrIO*) G__getstructoffset())->VertexEmr2Edb(*(EdbVertex*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrCint_563_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdbEmrIO*) G__getstructoffset())->Print();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrCint_563_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) EdbEmrIO::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrCint_563_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EdbEmrIO::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrCint_563_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) EdbEmrIO::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrCint_563_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      EdbEmrIO::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrCint_563_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdbEmrIO*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrCint_563_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EdbEmrIO::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrCint_563_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) EdbEmrIO::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrCint_563_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EdbEmrIO::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrCint_563_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) EdbEmrIO::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__EmrCint_563_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   EdbEmrIO* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new EdbEmrIO(*(EdbEmrIO*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__EmrCintLN_EdbEmrIO));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef EdbEmrIO G__TEdbEmrIO;
static int G__EmrCint_563_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (EdbEmrIO*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((EdbEmrIO*) (soff+(sizeof(EdbEmrIO)*i)))->~G__TEdbEmrIO();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (EdbEmrIO*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((EdbEmrIO*) (soff))->~G__TEdbEmrIO();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__EmrCint_563_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   EdbEmrIO* dest = (EdbEmrIO*) G__getstructoffset();
   *dest = *(EdbEmrIO*) libp->para[0].ref;
   const EdbEmrIO& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* EdbEmrFileAccess */
static int G__EmrCint_564_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   EdbEmrFileAccess* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new EdbEmrFileAccess[n];
     } else {
       p = new((void*) gvp) EdbEmrFileAccess[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new EdbEmrFileAccess;
     } else {
       p = new((void*) gvp) EdbEmrFileAccess;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__EmrCintLN_EdbEmrFileAccess));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrCint_564_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((EdbEmrFileAccess*) G__getstructoffset())->PlateID((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrCint_564_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((EdbEmrFileAccess*) G__getstructoffset())->SideID((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrCint_564_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((EdbEmrFileAccess*) G__getstructoffset())->AddEntry(
(int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (int) G__int(libp->para[3])
, (int) G__int(libp->para[4]), (float) G__double(libp->para[5])
, (float) G__double(libp->para[6]), (float) G__double(libp->para[7])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrCint_564_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((EdbEmrFileAccess*) G__getstructoffset())->GetPlateEntries((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, *(TArrayI*) libp->para[2].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrCint_564_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((EdbEmrFileAccess*) G__getstructoffset())->FirstPlate());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrCint_564_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((EdbEmrFileAccess*) G__getstructoffset())->LastPlate());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrCint_564_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdbEmrFileAccess*) G__getstructoffset())->PrintStat();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrCint_564_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((EdbEmrFileAccess*) G__getstructoffset())->SideID((int) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrCint_564_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) EdbEmrFileAccess::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrCint_564_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EdbEmrFileAccess::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrCint_564_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) EdbEmrFileAccess::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrCint_564_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      EdbEmrFileAccess::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrCint_564_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdbEmrFileAccess*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrCint_564_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EdbEmrFileAccess::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrCint_564_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) EdbEmrFileAccess::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrCint_564_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EdbEmrFileAccess::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrCint_564_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) EdbEmrFileAccess::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef EdbEmrFileAccess G__TEdbEmrFileAccess;
static int G__EmrCint_564_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (EdbEmrFileAccess*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((EdbEmrFileAccess*) (soff+(sizeof(EdbEmrFileAccess)*i)))->~G__TEdbEmrFileAccess();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (EdbEmrFileAccess*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((EdbEmrFileAccess*) (soff))->~G__TEdbEmrFileAccess();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* EdbEmrIO */

/* EdbEmrFileAccess */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncEmrCint {
 public:
  G__Sizep2memfuncEmrCint(): p(&G__Sizep2memfuncEmrCint::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncEmrCint::*p)();
};

size_t G__get_sizep2memfuncEmrCint()
{
  G__Sizep2memfuncEmrCint a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceEmrCint() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__EmrCintLN_EdbEmrIO))) {
     EdbEmrIO *G__Lderived;
     G__Lderived=(EdbEmrIO*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EmrCintLN_EdbEmrIO),G__get_linked_tagnum(&G__EmrCintLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__EmrCintLN_EdbEmrFileAccess))) {
     EdbEmrFileAccess *G__Lderived;
     G__Lderived=(EdbEmrFileAccess*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EmrCintLN_EdbEmrFileAccess),G__get_linked_tagnum(&G__EmrCintLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableEmrCint() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__EmrCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EmrCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EmrCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EmrCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EmrCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__EmrCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EmrCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EmrCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EmrCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EmrCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__EmrCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__EmrCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__EmrCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__EmrCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__EmrCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__EmrCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__EmrCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__EmrCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__EmrCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__EmrCintLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__EmrCintLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__EmrCintLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__EmrCintLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Double_t>",117,G__get_linked_tagnum(&G__EmrCintLN_TMatrixTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Double_t>",117,G__get_linked_tagnum(&G__EmrCintLN_TMatrixTRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Double_t>",117,G__get_linked_tagnum(&G__EmrCintLN_TMatrixTColumn_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Double_t>",117,G__get_linked_tagnum(&G__EmrCintLN_TMatrixTDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Double_t>",117,G__get_linked_tagnum(&G__EmrCintLN_TMatrixTFlat_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Double_t>",117,G__get_linked_tagnum(&G__EmrCintLN_TMatrixTSub_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Double_t>",117,G__get_linked_tagnum(&G__EmrCintLN_TMatrixTSparseRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Double_t>",117,G__get_linked_tagnum(&G__EmrCintLN_TMatrixTSparseDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Double_t>",117,G__get_linked_tagnum(&G__EmrCintLN_TMatrixTRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Double_t>",117,G__get_linked_tagnum(&G__EmrCintLN_TMatrixTColumnlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Double_t>",117,G__get_linked_tagnum(&G__EmrCintLN_TMatrixTDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Double_t>",117,G__get_linked_tagnum(&G__EmrCintLN_TMatrixTFlatlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Double_t>",117,G__get_linked_tagnum(&G__EmrCintLN_TMatrixTSublEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Double_t>",117,G__get_linked_tagnum(&G__EmrCintLN_TMatrixTSparseRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Double_t>",117,G__get_linked_tagnum(&G__EmrCintLN_TMatrixTSparseDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Double_t>",117,G__get_linked_tagnum(&G__EmrCintLN_TElementActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Double_t>",117,G__get_linked_tagnum(&G__EmrCintLN_TElementPosActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* EdbEmrIO */
static void G__setup_memvarEdbEmrIO(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__EmrCintLN_EdbEmrIO));
   { EdbEmrIO *p; p=(EdbEmrIO*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EmrCintLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* EdbEmrFileAccess */
static void G__setup_memvarEdbEmrFileAccess(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__EmrCintLN_EdbEmrFileAccess));
   { EdbEmrFileAccess *p; p=(EdbEmrFileAccess*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EmrCintLN_TObjArray),-1,-1,4,"eSides=",0,"each entry is EdbPattern with the views of one side ");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EmrCintLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarEmrCint() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncEdbEmrIO(void) {
   /* EdbEmrIO */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__EmrCintLN_EdbEmrIO));
   G__memfunc_setup("EdbEmrIO",711,G__EmrCint_563_0_1, 105, G__get_linked_tagnum(&G__EmrCintLN_EdbEmrIO), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TrackEdb2Emr",1110,G__EmrCint_563_0_2, 121, -1, -1, 0, 1, 1, 1, 0, "u 'EdbTrackP' - 1 - tedb", "(EdbTrackP &tedb, EmrTrack  &temr)", (void*) NULL, 0);
   G__memfunc_setup("TrackEmr2Edb",1110,G__EmrCint_563_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "u 'EdbTrackP' - 1 - tedb", "(EmrTrack  &temr, EdbTrackP &tedb)", (void*) NULL, 0);
   G__memfunc_setup("VertexEdb2Emr",1247,G__EmrCint_563_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "u 'EdbVertex' - 1 - vedb", "(EdbVeretx &vedb, EmrVeretx &vemr)", (void*) NULL, 0);
   G__memfunc_setup("VertexEmr2Edb",1247,G__EmrCint_563_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "u 'EdbVertex' - 1 - vedb", "(EmrVeretx &vemr, EdbVeretx &vedb)", (void*) NULL, 0);
   G__memfunc_setup("Print",525,G__EmrCint_563_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__EmrCint_563_0_7, 85, G__get_linked_tagnum(&G__EmrCintLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&EdbEmrIO::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__EmrCint_563_0_8, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EdbEmrIO::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__EmrCint_563_0_9, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&EdbEmrIO::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__EmrCint_563_0_10, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&EdbEmrIO::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__EmrCintLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__EmrCint_563_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__EmrCint_563_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EdbEmrIO::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__EmrCint_563_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&EdbEmrIO::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__EmrCint_563_0_17, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EdbEmrIO::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__EmrCint_563_0_18, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&EdbEmrIO::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("EdbEmrIO", 711, G__EmrCint_563_0_19, (int) ('i'), G__get_linked_tagnum(&G__EmrCintLN_EdbEmrIO), -1, 0, 1, 1, 1, 0, "u 'EdbEmrIO' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~EdbEmrIO", 837, G__EmrCint_563_0_20, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__EmrCint_563_0_21, (int) ('u'), G__get_linked_tagnum(&G__EmrCintLN_EdbEmrIO), -1, 1, 1, 1, 1, 0, "u 'EdbEmrIO' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncEdbEmrFileAccess(void) {
   /* EdbEmrFileAccess */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__EmrCintLN_EdbEmrFileAccess));
   G__memfunc_setup("EdbEmrFileAccess",1537,G__EmrCint_564_0_1, 105, G__get_linked_tagnum(&G__EmrCintLN_EdbEmrFileAccess), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlateID",643,G__EmrCint_564_0_2, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - plateside", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SideID",530,G__EmrCint_564_0_3, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - plateside", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddEntry",795,G__EmrCint_564_0_4, 85, G__get_linked_tagnum(&G__EmrCintLN_EdbSegP), -1, 0, 8, 1, 1, 0, 
"i - - 0 - plate i - - 0 - side "
"i - - 0 - zone i - - 0 - view "
"i - - 0 - entry f - - 0 - x "
"f - - 0 - y f - - 0 - z", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPlateEntries",1520,G__EmrCint_564_0_5, 105, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - plate i - - 0 - side "
"u 'TArrayI' - 1 - entries", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FirstPlate",1022,G__EmrCint_564_0_6, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LastPlate",906,G__EmrCint_564_0_7, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintStat",937,G__EmrCint_564_0_8, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SideID",530,G__EmrCint_564_0_9, 105, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - plate i - - 0 - side", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__EmrCint_564_0_10, 85, G__get_linked_tagnum(&G__EmrCintLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&EdbEmrFileAccess::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__EmrCint_564_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EdbEmrFileAccess::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__EmrCint_564_0_12, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&EdbEmrFileAccess::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__EmrCint_564_0_13, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&EdbEmrFileAccess::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__EmrCintLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__EmrCint_564_0_17, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__EmrCint_564_0_18, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EdbEmrFileAccess::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__EmrCint_564_0_19, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&EdbEmrFileAccess::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__EmrCint_564_0_20, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EdbEmrFileAccess::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__EmrCint_564_0_21, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&EdbEmrFileAccess::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~EdbEmrFileAccess", 1663, G__EmrCint_564_0_22, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncEmrCint() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalEmrCint() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcEmrCint() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__EmrCintLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_TObjArray = { "TObjArray" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_TArrayI = { "TArrayI" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__EmrCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_TElementActionTlEdoublegR = { "TElementActionT<double>" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_TElementPosActionTlEdoublegR = { "TElementPosActionT<double>" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_TMatrixTlEdoublegR = { "TMatrixT<double>" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_TMatrixTRow_constlEdoublegR = { "TMatrixTRow_const<double>" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_TMatrixTRowlEdoublegR = { "TMatrixTRow<double>" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_TMatrixTDiag_constlEdoublegR = { "TMatrixTDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_TMatrixTColumn_constlEdoublegR = { "TMatrixTColumn_const<double>" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_TMatrixTFlat_constlEdoublegR = { "TMatrixTFlat_const<double>" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_TMatrixTSub_constlEdoublegR = { "TMatrixTSub_const<double>" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_TMatrixTSparseRow_constlEdoublegR = { "TMatrixTSparseRow_const<double>" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_TMatrixTSparseDiag_constlEdoublegR = { "TMatrixTSparseDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_TMatrixTColumnlEdoublegR = { "TMatrixTColumn<double>" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_TMatrixTDiaglEdoublegR = { "TMatrixTDiag<double>" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_TMatrixTFlatlEdoublegR = { "TMatrixTFlat<double>" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_TMatrixTSublEdoublegR = { "TMatrixTSub<double>" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_TMatrixTSparseRowlEdoublegR = { "TMatrixTSparseRow<double>" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_TMatrixTSparseDiaglEdoublegR = { "TMatrixTSparseDiag<double>" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_EdbSegP = { "EdbSegP" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_EdbVertex = { "EdbVertex" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_EdbTrackP = { "EdbTrackP" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_EdbEmrIO = { "EdbEmrIO" , 99 , -1 };
G__linked_taginfo G__EmrCintLN_EdbEmrFileAccess = { "EdbEmrFileAccess" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableEmrCint() {
  G__EmrCintLN_TClass.tagnum = -1 ;
  G__EmrCintLN_TBuffer.tagnum = -1 ;
  G__EmrCintLN_TMemberInspector.tagnum = -1 ;
  G__EmrCintLN_TObject.tagnum = -1 ;
  G__EmrCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__EmrCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EmrCintLN_TObjArray.tagnum = -1 ;
  G__EmrCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__EmrCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EmrCintLN_TArrayI.tagnum = -1 ;
  G__EmrCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__EmrCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__EmrCintLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__EmrCintLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__EmrCintLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__EmrCintLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__EmrCintLN_TElementActionTlEdoublegR.tagnum = -1 ;
  G__EmrCintLN_TElementPosActionTlEdoublegR.tagnum = -1 ;
  G__EmrCintLN_TMatrixTlEdoublegR.tagnum = -1 ;
  G__EmrCintLN_TMatrixTRow_constlEdoublegR.tagnum = -1 ;
  G__EmrCintLN_TMatrixTRowlEdoublegR.tagnum = -1 ;
  G__EmrCintLN_TMatrixTDiag_constlEdoublegR.tagnum = -1 ;
  G__EmrCintLN_TMatrixTColumn_constlEdoublegR.tagnum = -1 ;
  G__EmrCintLN_TMatrixTFlat_constlEdoublegR.tagnum = -1 ;
  G__EmrCintLN_TMatrixTSub_constlEdoublegR.tagnum = -1 ;
  G__EmrCintLN_TMatrixTSparseRow_constlEdoublegR.tagnum = -1 ;
  G__EmrCintLN_TMatrixTSparseDiag_constlEdoublegR.tagnum = -1 ;
  G__EmrCintLN_TMatrixTColumnlEdoublegR.tagnum = -1 ;
  G__EmrCintLN_TMatrixTDiaglEdoublegR.tagnum = -1 ;
  G__EmrCintLN_TMatrixTFlatlEdoublegR.tagnum = -1 ;
  G__EmrCintLN_TMatrixTSublEdoublegR.tagnum = -1 ;
  G__EmrCintLN_TMatrixTSparseRowlEdoublegR.tagnum = -1 ;
  G__EmrCintLN_TMatrixTSparseDiaglEdoublegR.tagnum = -1 ;
  G__EmrCintLN_EdbSegP.tagnum = -1 ;
  G__EmrCintLN_EdbVertex.tagnum = -1 ;
  G__EmrCintLN_EdbTrackP.tagnum = -1 ;
  G__EmrCintLN_EdbEmrIO.tagnum = -1 ;
  G__EmrCintLN_EdbEmrFileAccess.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableEmrCint() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__EmrCintLN_TClass);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_TObject);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_TObjArray);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_TArrayI);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_TElementActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_TElementPosActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_TMatrixTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_TMatrixTRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_TMatrixTRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_TMatrixTDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_TMatrixTColumn_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_TMatrixTFlat_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_TMatrixTSub_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_TMatrixTSparseRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_TMatrixTSparseDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_TMatrixTColumnlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_TMatrixTDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_TMatrixTFlatlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_TMatrixTSublEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_TMatrixTSparseRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_TMatrixTSparseDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_EdbSegP);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_EdbVertex);
   G__get_linked_tagnum_fwd(&G__EmrCintLN_EdbTrackP);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__EmrCintLN_EdbEmrIO),sizeof(EdbEmrIO),-1,29952,"interface between FEDRA and EmuRec objects",G__setup_memvarEdbEmrIO,G__setup_memfuncEdbEmrIO);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__EmrCintLN_EdbEmrFileAccess),sizeof(EdbEmrFileAccess),-1,29952,"to manage better plane emurec file structure",G__setup_memvarEdbEmrFileAccess,G__setup_memfuncEdbEmrFileAccess);
}
extern "C" void G__cpp_setupEmrCint(void) {
  G__check_setup_version(30051515,"G__cpp_setupEmrCint()");
  G__set_cpp_environmentEmrCint();
  G__cpp_setup_tagtableEmrCint();

  G__cpp_setup_inheritanceEmrCint();

  G__cpp_setup_typetableEmrCint();

  G__cpp_setup_memvarEmrCint();

  G__cpp_setup_memfuncEmrCint();
  G__cpp_setup_globalEmrCint();
  G__cpp_setup_funcEmrCint();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncEmrCint();
  return;
}
class G__cpp_setup_initEmrCint {
  public:
    G__cpp_setup_initEmrCint() { G__add_setup_func("EmrCint",(G__incsetup)(&G__cpp_setupEmrCint)); G__call_setup_funcs(); }
   ~G__cpp_setup_initEmrCint() { G__remove_setup_func("EmrCint"); }
};
G__cpp_setup_initEmrCint G__cpp_setup_initializerEmrCint;

