//
// File generated by C:\root_v5.34.38\bin\rootcint.EXE at Tue Jun 02 09:12:35 2020

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME EmrDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "EmrDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void EdbEmrIO_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_EdbEmrIO(void *p = 0);
   static void *newArray_EdbEmrIO(Long_t size, void *p);
   static void delete_EdbEmrIO(void *p);
   static void deleteArray_EdbEmrIO(void *p);
   static void destruct_EdbEmrIO(void *p);
   static void streamer_EdbEmrIO(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::EdbEmrIO*)
   {
      ::EdbEmrIO *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::EdbEmrIO >(0);
      static ::ROOT::TGenericClassInfo 
         instance("EdbEmrIO", ::EdbEmrIO::Class_Version(), "./EdbEmrIO.h", 20,
                  typeid(::EdbEmrIO), ::ROOT::DefineBehavior(ptr, ptr),
                  &::EdbEmrIO::Dictionary, isa_proxy, 0,
                  sizeof(::EdbEmrIO) );
      instance.SetNew(&new_EdbEmrIO);
      instance.SetNewArray(&newArray_EdbEmrIO);
      instance.SetDelete(&delete_EdbEmrIO);
      instance.SetDeleteArray(&deleteArray_EdbEmrIO);
      instance.SetDestructor(&destruct_EdbEmrIO);
      instance.SetStreamerFunc(&streamer_EdbEmrIO);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::EdbEmrIO*)
   {
      return GenerateInitInstanceLocal((::EdbEmrIO*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::EdbEmrIO*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

namespace ROOTDict {
   void EdbEmrFileAccess_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_EdbEmrFileAccess(void *p = 0);
   static void *newArray_EdbEmrFileAccess(Long_t size, void *p);
   static void delete_EdbEmrFileAccess(void *p);
   static void deleteArray_EdbEmrFileAccess(void *p);
   static void destruct_EdbEmrFileAccess(void *p);
   static void streamer_EdbEmrFileAccess(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::EdbEmrFileAccess*)
   {
      ::EdbEmrFileAccess *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::EdbEmrFileAccess >(0);
      static ::ROOT::TGenericClassInfo 
         instance("EdbEmrFileAccess", ::EdbEmrFileAccess::Class_Version(), "./EdbEmrIO.h", 39,
                  typeid(::EdbEmrFileAccess), ::ROOT::DefineBehavior(ptr, ptr),
                  &::EdbEmrFileAccess::Dictionary, isa_proxy, 0,
                  sizeof(::EdbEmrFileAccess) );
      instance.SetNew(&new_EdbEmrFileAccess);
      instance.SetNewArray(&newArray_EdbEmrFileAccess);
      instance.SetDelete(&delete_EdbEmrFileAccess);
      instance.SetDeleteArray(&deleteArray_EdbEmrFileAccess);
      instance.SetDestructor(&destruct_EdbEmrFileAccess);
      instance.SetStreamerFunc(&streamer_EdbEmrFileAccess);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::EdbEmrFileAccess*)
   {
      return GenerateInitInstanceLocal((::EdbEmrFileAccess*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::EdbEmrFileAccess*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr EdbEmrIO::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *EdbEmrIO::Class_Name()
{
   return "EdbEmrIO";
}

//______________________________________________________________________________
const char *EdbEmrIO::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::EdbEmrIO*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int EdbEmrIO::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::EdbEmrIO*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void EdbEmrIO::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::EdbEmrIO*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *EdbEmrIO::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::EdbEmrIO*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
atomic_TClass_ptr EdbEmrFileAccess::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *EdbEmrFileAccess::Class_Name()
{
   return "EdbEmrFileAccess";
}

//______________________________________________________________________________
const char *EdbEmrFileAccess::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::EdbEmrFileAccess*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int EdbEmrFileAccess::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::EdbEmrFileAccess*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void EdbEmrFileAccess::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::EdbEmrFileAccess*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *EdbEmrFileAccess::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::EdbEmrFileAccess*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void EdbEmrIO::Streamer(TBuffer &R__b)
{
   // Stream an object of class EdbEmrIO.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b.CheckByteCount(R__s, R__c, EdbEmrIO::IsA());
   } else {
      R__c = R__b.WriteVersion(EdbEmrIO::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void EdbEmrIO::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class EdbEmrIO.
      typedef ::EdbEmrIO msvc_bug_workaround;
      TClass *R__cl = msvc_bug_workaround::IsA();
      if (R__cl || R__insp.IsA()) { }
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_EdbEmrIO(void *p) {
      return  p ? new(p) ::EdbEmrIO : new ::EdbEmrIO;
   }
   static void *newArray_EdbEmrIO(Long_t nElements, void *p) {
      return p ? new(p) ::EdbEmrIO[nElements] : new ::EdbEmrIO[nElements];
   }
   // Wrapper around operator delete
   static void delete_EdbEmrIO(void *p) {
      delete ((::EdbEmrIO*)p);
   }
   static void deleteArray_EdbEmrIO(void *p) {
      delete [] ((::EdbEmrIO*)p);
   }
   static void destruct_EdbEmrIO(void *p) {
      typedef ::EdbEmrIO current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_EdbEmrIO(TBuffer &buf, void *obj) {
      ((::EdbEmrIO*)obj)->::EdbEmrIO::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::EdbEmrIO

//______________________________________________________________________________
void EdbEmrFileAccess::Streamer(TBuffer &R__b)
{
   // Stream an object of class EdbEmrFileAccess.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      eSides.Streamer(R__b);
      R__b.CheckByteCount(R__s, R__c, EdbEmrFileAccess::IsA());
   } else {
      R__c = R__b.WriteVersion(EdbEmrFileAccess::IsA(), kTRUE);
      TObject::Streamer(R__b);
      eSides.Streamer(R__b);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void EdbEmrFileAccess::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class EdbEmrFileAccess.
      typedef ::EdbEmrFileAccess msvc_bug_workaround;
      TClass *R__cl = msvc_bug_workaround::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "eSides", &eSides);
      R__insp.InspectMember(eSides, "eSides.");
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_EdbEmrFileAccess(void *p) {
      return  p ? new(p) ::EdbEmrFileAccess : new ::EdbEmrFileAccess;
   }
   static void *newArray_EdbEmrFileAccess(Long_t nElements, void *p) {
      return p ? new(p) ::EdbEmrFileAccess[nElements] : new ::EdbEmrFileAccess[nElements];
   }
   // Wrapper around operator delete
   static void delete_EdbEmrFileAccess(void *p) {
      delete ((::EdbEmrFileAccess*)p);
   }
   static void deleteArray_EdbEmrFileAccess(void *p) {
      delete [] ((::EdbEmrFileAccess*)p);
   }
   static void destruct_EdbEmrFileAccess(void *p) {
      typedef ::EdbEmrFileAccess current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_EdbEmrFileAccess(TBuffer &buf, void *obj) {
      ((::EdbEmrFileAccess*)obj)->::EdbEmrFileAccess::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::EdbEmrFileAccess

/********************************************************
* EmrDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtableEmrDict();

extern "C" void G__set_cpp_environmentEmrDict() {
  G__add_ipath(".");
  G__add_ipath("..\\..\\include");
  G__cpp_reset_tagtableEmrDict();
}
#include <new>
extern "C" int G__cpp_dllrevEmrDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* EdbEmrIO */
static int G__EmrDict_603_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   EdbEmrIO* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new EdbEmrIO[n];
     } else {
       p = new((void*) gvp) EdbEmrIO[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new EdbEmrIO;
     } else {
       p = new((void*) gvp) EdbEmrIO;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__EmrDictLN_EdbEmrIO));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrDict_603_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdbEmrIO*) G__getstructoffset())->TrackEdb2Emr(*(EdbTrackP*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrDict_603_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdbEmrIO*) G__getstructoffset())->TrackEmr2Edb(*(EdbTrackP*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrDict_603_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdbEmrIO*) G__getstructoffset())->VertexEdb2Emr(*(EdbVertex*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrDict_603_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdbEmrIO*) G__getstructoffset())->VertexEmr2Edb(*(EdbVertex*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrDict_603_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdbEmrIO*) G__getstructoffset())->Print();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrDict_603_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) EdbEmrIO::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrDict_603_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EdbEmrIO::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrDict_603_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) EdbEmrIO::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrDict_603_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      EdbEmrIO::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrDict_603_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdbEmrIO*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrDict_603_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EdbEmrIO::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrDict_603_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) EdbEmrIO::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrDict_603_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EdbEmrIO::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrDict_603_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) EdbEmrIO::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__EmrDict_603_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   EdbEmrIO* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new EdbEmrIO(*(EdbEmrIO*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__EmrDictLN_EdbEmrIO));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef EdbEmrIO G__TEdbEmrIO;
static int G__EmrDict_603_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (EdbEmrIO*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((EdbEmrIO*) (soff+(sizeof(EdbEmrIO)*i)))->~G__TEdbEmrIO();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (EdbEmrIO*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((EdbEmrIO*) (soff))->~G__TEdbEmrIO();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__EmrDict_603_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   EdbEmrIO* dest = (EdbEmrIO*) G__getstructoffset();
   *dest = *(EdbEmrIO*) libp->para[0].ref;
   const EdbEmrIO& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* EdbEmrFileAccess */
static int G__EmrDict_604_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   EdbEmrFileAccess* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new EdbEmrFileAccess[n];
     } else {
       p = new((void*) gvp) EdbEmrFileAccess[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new EdbEmrFileAccess;
     } else {
       p = new((void*) gvp) EdbEmrFileAccess;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__EmrDictLN_EdbEmrFileAccess));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrDict_604_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((EdbEmrFileAccess*) G__getstructoffset())->PlateID((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrDict_604_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((EdbEmrFileAccess*) G__getstructoffset())->SideID((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrDict_604_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((EdbEmrFileAccess*) G__getstructoffset())->AddEntry(
(int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (int) G__int(libp->para[3])
, (int) G__int(libp->para[4]), (float) G__double(libp->para[5])
, (float) G__double(libp->para[6]), (float) G__double(libp->para[7])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrDict_604_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((EdbEmrFileAccess*) G__getstructoffset())->GetPlateEntries((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, *(TArrayI*) libp->para[2].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrDict_604_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((EdbEmrFileAccess*) G__getstructoffset())->FirstPlate());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrDict_604_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((EdbEmrFileAccess*) G__getstructoffset())->LastPlate());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrDict_604_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdbEmrFileAccess*) G__getstructoffset())->PrintStat();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrDict_604_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((EdbEmrFileAccess*) G__getstructoffset())->SideID((int) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrDict_604_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) EdbEmrFileAccess::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrDict_604_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EdbEmrFileAccess::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrDict_604_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) EdbEmrFileAccess::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrDict_604_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      EdbEmrFileAccess::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrDict_604_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdbEmrFileAccess*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrDict_604_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EdbEmrFileAccess::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrDict_604_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) EdbEmrFileAccess::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrDict_604_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EdbEmrFileAccess::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EmrDict_604_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) EdbEmrFileAccess::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef EdbEmrFileAccess G__TEdbEmrFileAccess;
static int G__EmrDict_604_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (EdbEmrFileAccess*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((EdbEmrFileAccess*) (soff+(sizeof(EdbEmrFileAccess)*i)))->~G__TEdbEmrFileAccess();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (EdbEmrFileAccess*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((EdbEmrFileAccess*) (soff))->~G__TEdbEmrFileAccess();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* EdbEmrIO */

/* EdbEmrFileAccess */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncEmrDict {
 public:
  G__Sizep2memfuncEmrDict(): p(&G__Sizep2memfuncEmrDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncEmrDict::*p)();
};

size_t G__get_sizep2memfuncEmrDict()
{
  G__Sizep2memfuncEmrDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceEmrDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__EmrDictLN_EdbEmrIO))) {
     EdbEmrIO *G__Lderived;
     G__Lderived=(EdbEmrIO*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EmrDictLN_EdbEmrIO),G__get_linked_tagnum(&G__EmrDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__EmrDictLN_EdbEmrFileAccess))) {
     EdbEmrFileAccess *G__Lderived;
     G__Lderived=(EdbEmrFileAccess*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EmrDictLN_EdbEmrFileAccess),G__get_linked_tagnum(&G__EmrDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableEmrDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("iterator<iterator_traits<string::iterator>::iterator_category,iterator_traits<string::iterator>::value_type,iterator_traits<string::iterator>::difference_type,iterator_traits<string::iterator>::pointer,iterator_traits<string::iterator>::reference>",117,G__get_linked_tagnum(&G__EmrDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,char>",117,G__get_linked_tagnum(&G__EmrDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,char,long>",117,G__get_linked_tagnum(&G__EmrDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,char,long,char*>",117,G__get_linked_tagnum(&G__EmrDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<string::const_iterator>::iterator_category,iterator_traits<string::const_iterator>::value_type,iterator_traits<string::const_iterator>::difference_type,iterator_traits<string::const_iterator>::pointer,iterator_traits<string::const_iterator>::reference>",117,G__get_linked_tagnum(&G__EmrDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__EmrDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__EmrDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EmrDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EmrDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::iterator_category,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::value_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::difference_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::pointer,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::reference>",117,G__get_linked_tagnum(&G__EmrDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__EmrDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long>",117,G__get_linked_tagnum(&G__EmrDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long,ROOT::TSchemaHelper*>",117,G__get_linked_tagnum(&G__EmrDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EmrDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR),0,G__get_linked_tagnum(&G__EmrDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::iterator_category,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::value_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::difference_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::pointer,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::reference>",117,G__get_linked_tagnum(&G__EmrDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__EmrDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__EmrDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EmrDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EmrDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::iterator_category,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::value_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::difference_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::pointer,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::reference>",117,G__get_linked_tagnum(&G__EmrDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TVirtualArray*>",117,G__get_linked_tagnum(&G__EmrDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TVirtualArray*,long>",117,G__get_linked_tagnum(&G__EmrDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TVirtualArray*,long,TVirtualArray**>",117,G__get_linked_tagnum(&G__EmrDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EmrDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR),0,G__get_linked_tagnum(&G__EmrDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::iterator_category,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::value_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::difference_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::pointer,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::reference>",117,G__get_linked_tagnum(&G__EmrDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__EmrDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__EmrDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__EmrDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__EmrDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__EmrDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__EmrDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__EmrDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__EmrDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__EmrDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__EmrDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__EmrDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__EmrDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__EmrDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Double_t>",117,G__get_linked_tagnum(&G__EmrDictLN_TMatrixTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Double_t>",117,G__get_linked_tagnum(&G__EmrDictLN_TMatrixTRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Double_t>",117,G__get_linked_tagnum(&G__EmrDictLN_TMatrixTColumn_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Double_t>",117,G__get_linked_tagnum(&G__EmrDictLN_TMatrixTDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Double_t>",117,G__get_linked_tagnum(&G__EmrDictLN_TMatrixTFlat_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Double_t>",117,G__get_linked_tagnum(&G__EmrDictLN_TMatrixTSub_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Double_t>",117,G__get_linked_tagnum(&G__EmrDictLN_TMatrixTSparseRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Double_t>",117,G__get_linked_tagnum(&G__EmrDictLN_TMatrixTSparseDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Double_t>",117,G__get_linked_tagnum(&G__EmrDictLN_TMatrixTRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Double_t>",117,G__get_linked_tagnum(&G__EmrDictLN_TMatrixTColumnlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Double_t>",117,G__get_linked_tagnum(&G__EmrDictLN_TMatrixTDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Double_t>",117,G__get_linked_tagnum(&G__EmrDictLN_TMatrixTFlatlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Double_t>",117,G__get_linked_tagnum(&G__EmrDictLN_TMatrixTSublEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Double_t>",117,G__get_linked_tagnum(&G__EmrDictLN_TMatrixTSparseRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Double_t>",117,G__get_linked_tagnum(&G__EmrDictLN_TMatrixTSparseDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Double_t>",117,G__get_linked_tagnum(&G__EmrDictLN_TElementActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Double_t>",117,G__get_linked_tagnum(&G__EmrDictLN_TElementPosActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* EdbEmrIO */
static void G__setup_memvarEdbEmrIO(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__EmrDictLN_EdbEmrIO));
   { EdbEmrIO *p; p=(EdbEmrIO*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EmrDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* EdbEmrFileAccess */
static void G__setup_memvarEdbEmrFileAccess(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__EmrDictLN_EdbEmrFileAccess));
   { EdbEmrFileAccess *p; p=(EdbEmrFileAccess*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EmrDictLN_TObjArray),-1,-1,4,"eSides=",0,"each entry is EdbPattern with the views of one side ");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EmrDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarEmrDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncEdbEmrIO(void) {
   /* EdbEmrIO */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__EmrDictLN_EdbEmrIO));
   G__memfunc_setup("EdbEmrIO",711,G__EmrDict_603_0_1, 105, G__get_linked_tagnum(&G__EmrDictLN_EdbEmrIO), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TrackEdb2Emr",1110,G__EmrDict_603_0_2, 121, -1, -1, 0, 1, 1, 1, 0, "u 'EdbTrackP' - 1 - tedb", "(EdbTrackP &tedb, EmrTrack  &temr)", (void*) NULL, 0);
   G__memfunc_setup("TrackEmr2Edb",1110,G__EmrDict_603_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "u 'EdbTrackP' - 1 - tedb", "(EmrTrack  &temr, EdbTrackP &tedb)", (void*) NULL, 0);
   G__memfunc_setup("VertexEdb2Emr",1247,G__EmrDict_603_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "u 'EdbVertex' - 1 - vedb", "(EdbVeretx &vedb, EmrVeretx &vemr)", (void*) NULL, 0);
   G__memfunc_setup("VertexEmr2Edb",1247,G__EmrDict_603_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "u 'EdbVertex' - 1 - vedb", "(EmrVeretx &vemr, EdbVeretx &vedb)", (void*) NULL, 0);
   G__memfunc_setup("Print",525,G__EmrDict_603_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__EmrDict_603_0_7, 85, G__get_linked_tagnum(&G__EmrDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&EdbEmrIO::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__EmrDict_603_0_8, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EdbEmrIO::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__EmrDict_603_0_9, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&EdbEmrIO::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__EmrDict_603_0_10, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&EdbEmrIO::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__EmrDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__EmrDict_603_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__EmrDict_603_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EdbEmrIO::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__EmrDict_603_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&EdbEmrIO::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__EmrDict_603_0_17, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EdbEmrIO::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__EmrDict_603_0_18, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&EdbEmrIO::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("EdbEmrIO", 711, G__EmrDict_603_0_19, (int) ('i'), G__get_linked_tagnum(&G__EmrDictLN_EdbEmrIO), -1, 0, 1, 1, 1, 0, "u 'EdbEmrIO' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~EdbEmrIO", 837, G__EmrDict_603_0_20, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__EmrDict_603_0_21, (int) ('u'), G__get_linked_tagnum(&G__EmrDictLN_EdbEmrIO), -1, 1, 1, 1, 1, 0, "u 'EdbEmrIO' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncEdbEmrFileAccess(void) {
   /* EdbEmrFileAccess */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__EmrDictLN_EdbEmrFileAccess));
   G__memfunc_setup("EdbEmrFileAccess",1537,G__EmrDict_604_0_1, 105, G__get_linked_tagnum(&G__EmrDictLN_EdbEmrFileAccess), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlateID",643,G__EmrDict_604_0_2, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - plateside", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SideID",530,G__EmrDict_604_0_3, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - plateside", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddEntry",795,G__EmrDict_604_0_4, 85, G__get_linked_tagnum(&G__EmrDictLN_EdbSegP), -1, 0, 8, 1, 1, 0, 
"i - - 0 - plate i - - 0 - side "
"i - - 0 - zone i - - 0 - view "
"i - - 0 - entry f - - 0 - x "
"f - - 0 - y f - - 0 - z", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPlateEntries",1520,G__EmrDict_604_0_5, 105, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - plate i - - 0 - side "
"u 'TArrayI' - 1 - entries", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FirstPlate",1022,G__EmrDict_604_0_6, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LastPlate",906,G__EmrDict_604_0_7, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintStat",937,G__EmrDict_604_0_8, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SideID",530,G__EmrDict_604_0_9, 105, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - plate i - - 0 - side", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__EmrDict_604_0_10, 85, G__get_linked_tagnum(&G__EmrDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&EdbEmrFileAccess::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__EmrDict_604_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EdbEmrFileAccess::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__EmrDict_604_0_12, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&EdbEmrFileAccess::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__EmrDict_604_0_13, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&EdbEmrFileAccess::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__EmrDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__EmrDict_604_0_17, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__EmrDict_604_0_18, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EdbEmrFileAccess::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__EmrDict_604_0_19, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&EdbEmrFileAccess::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__EmrDict_604_0_20, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EdbEmrFileAccess::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__EmrDict_604_0_21, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&EdbEmrFileAccess::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~EdbEmrFileAccess", 1663, G__EmrDict_604_0_22, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncEmrDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalEmrDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcEmrDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__EmrDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR = { "iterator<random_access_iterator_tag,char,long,char*,char&>" , 115 , -1 };
G__linked_taginfo G__EmrDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR = { "iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long,ROOT::TSchemaHelper*,ROOT::TSchemaHelper&>" , 115 , -1 };
G__linked_taginfo G__EmrDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_TObjArray = { "TObjArray" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR = { "iterator<random_access_iterator_tag,TVirtualArray*,long,TVirtualArray**,TVirtualArray*&>" , 115 , -1 };
G__linked_taginfo G__EmrDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_TArrayI = { "TArrayI" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__EmrDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_TElementActionTlEdoublegR = { "TElementActionT<double>" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_TElementPosActionTlEdoublegR = { "TElementPosActionT<double>" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_TMatrixTlEdoublegR = { "TMatrixT<double>" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_TMatrixTRow_constlEdoublegR = { "TMatrixTRow_const<double>" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_TMatrixTRowlEdoublegR = { "TMatrixTRow<double>" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_TMatrixTDiag_constlEdoublegR = { "TMatrixTDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_TMatrixTColumn_constlEdoublegR = { "TMatrixTColumn_const<double>" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_TMatrixTFlat_constlEdoublegR = { "TMatrixTFlat_const<double>" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_TMatrixTSub_constlEdoublegR = { "TMatrixTSub_const<double>" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_TMatrixTSparseRow_constlEdoublegR = { "TMatrixTSparseRow_const<double>" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_TMatrixTSparseDiag_constlEdoublegR = { "TMatrixTSparseDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_TMatrixTColumnlEdoublegR = { "TMatrixTColumn<double>" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_TMatrixTDiaglEdoublegR = { "TMatrixTDiag<double>" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_TMatrixTFlatlEdoublegR = { "TMatrixTFlat<double>" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_TMatrixTSublEdoublegR = { "TMatrixTSub<double>" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_TMatrixTSparseRowlEdoublegR = { "TMatrixTSparseRow<double>" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_TMatrixTSparseDiaglEdoublegR = { "TMatrixTSparseDiag<double>" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_EdbSegP = { "EdbSegP" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_EdbVertex = { "EdbVertex" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_EdbTrackP = { "EdbTrackP" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_EdbEmrIO = { "EdbEmrIO" , 99 , -1 };
G__linked_taginfo G__EmrDictLN_EdbEmrFileAccess = { "EdbEmrFileAccess" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableEmrDict() {
  G__EmrDictLN_TClass.tagnum = -1 ;
  G__EmrDictLN_TBuffer.tagnum = -1 ;
  G__EmrDictLN_TMemberInspector.tagnum = -1 ;
  G__EmrDictLN_TObject.tagnum = -1 ;
  G__EmrDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR.tagnum = -1 ;
  G__EmrDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__EmrDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EmrDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR.tagnum = -1 ;
  G__EmrDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR.tagnum = -1 ;
  G__EmrDictLN_TObjArray.tagnum = -1 ;
  G__EmrDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__EmrDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EmrDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR.tagnum = -1 ;
  G__EmrDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR.tagnum = -1 ;
  G__EmrDictLN_TArrayI.tagnum = -1 ;
  G__EmrDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__EmrDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__EmrDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__EmrDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__EmrDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__EmrDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__EmrDictLN_TElementActionTlEdoublegR.tagnum = -1 ;
  G__EmrDictLN_TElementPosActionTlEdoublegR.tagnum = -1 ;
  G__EmrDictLN_TMatrixTlEdoublegR.tagnum = -1 ;
  G__EmrDictLN_TMatrixTRow_constlEdoublegR.tagnum = -1 ;
  G__EmrDictLN_TMatrixTRowlEdoublegR.tagnum = -1 ;
  G__EmrDictLN_TMatrixTDiag_constlEdoublegR.tagnum = -1 ;
  G__EmrDictLN_TMatrixTColumn_constlEdoublegR.tagnum = -1 ;
  G__EmrDictLN_TMatrixTFlat_constlEdoublegR.tagnum = -1 ;
  G__EmrDictLN_TMatrixTSub_constlEdoublegR.tagnum = -1 ;
  G__EmrDictLN_TMatrixTSparseRow_constlEdoublegR.tagnum = -1 ;
  G__EmrDictLN_TMatrixTSparseDiag_constlEdoublegR.tagnum = -1 ;
  G__EmrDictLN_TMatrixTColumnlEdoublegR.tagnum = -1 ;
  G__EmrDictLN_TMatrixTDiaglEdoublegR.tagnum = -1 ;
  G__EmrDictLN_TMatrixTFlatlEdoublegR.tagnum = -1 ;
  G__EmrDictLN_TMatrixTSublEdoublegR.tagnum = -1 ;
  G__EmrDictLN_TMatrixTSparseRowlEdoublegR.tagnum = -1 ;
  G__EmrDictLN_TMatrixTSparseDiaglEdoublegR.tagnum = -1 ;
  G__EmrDictLN_EdbSegP.tagnum = -1 ;
  G__EmrDictLN_EdbVertex.tagnum = -1 ;
  G__EmrDictLN_EdbTrackP.tagnum = -1 ;
  G__EmrDictLN_EdbEmrIO.tagnum = -1 ;
  G__EmrDictLN_EdbEmrFileAccess.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableEmrDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__EmrDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_TObjArray);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_TArrayI);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_TElementActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_TElementPosActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_TMatrixTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_TMatrixTRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_TMatrixTRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_TMatrixTDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_TMatrixTColumn_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_TMatrixTFlat_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_TMatrixTSub_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_TMatrixTSparseRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_TMatrixTSparseDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_TMatrixTColumnlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_TMatrixTDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_TMatrixTFlatlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_TMatrixTSublEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_TMatrixTSparseRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_TMatrixTSparseDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_EdbSegP);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_EdbVertex);
   G__get_linked_tagnum_fwd(&G__EmrDictLN_EdbTrackP);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__EmrDictLN_EdbEmrIO),sizeof(EdbEmrIO),-1,29952,"interface between FEDRA and EmuRec objects",G__setup_memvarEdbEmrIO,G__setup_memfuncEdbEmrIO);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__EmrDictLN_EdbEmrFileAccess),sizeof(EdbEmrFileAccess),-1,29952,"to manage better plane emurec file structure",G__setup_memvarEdbEmrFileAccess,G__setup_memfuncEdbEmrFileAccess);
}
extern "C" void G__cpp_setupEmrDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupEmrDict()");
  G__set_cpp_environmentEmrDict();
  G__cpp_setup_tagtableEmrDict();

  G__cpp_setup_inheritanceEmrDict();

  G__cpp_setup_typetableEmrDict();

  G__cpp_setup_memvarEmrDict();

  G__cpp_setup_memfuncEmrDict();
  G__cpp_setup_globalEmrDict();
  G__cpp_setup_funcEmrDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncEmrDict();
  return;
}
class G__cpp_setup_initEmrDict {
  public:
    G__cpp_setup_initEmrDict() { G__add_setup_func("EmrDict",(G__incsetup)(&G__cpp_setupEmrDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initEmrDict() { G__remove_setup_func("EmrDict"); }
};
G__cpp_setup_initEmrDict G__cpp_setup_initializerEmrDict;

