/********************************************************************
* EmrDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error EmrDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern G__DLLEXPORT int G__cpp_dllrevEmrDict();
extern G__DLLEXPORT void G__set_cpp_environmentEmrDict();
extern G__DLLEXPORT void G__cpp_setup_tagtableEmrDict();
extern G__DLLEXPORT void G__cpp_setup_inheritanceEmrDict();
extern G__DLLEXPORT void G__cpp_setup_typetableEmrDict();
extern G__DLLEXPORT void G__cpp_setup_memvarEmrDict();
extern G__DLLEXPORT void G__cpp_setup_globalEmrDict();
extern G__DLLEXPORT void G__cpp_setup_memfuncEmrDict();
extern G__DLLEXPORT void G__cpp_setup_funcEmrDict();
extern G__DLLEXPORT void G__cpp_setupEmrDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "EdbEmrIO.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EmrDictLN_TClass;
extern G__linked_taginfo G__EmrDictLN_TBuffer;
extern G__linked_taginfo G__EmrDictLN_TMemberInspector;
extern G__linked_taginfo G__EmrDictLN_TObject;
extern G__linked_taginfo G__EmrDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR;
extern G__linked_taginfo G__EmrDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EmrDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EmrDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__EmrDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__EmrDictLN_TObjArray;
extern G__linked_taginfo G__EmrDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EmrDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EmrDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR;
extern G__linked_taginfo G__EmrDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__EmrDictLN_TArrayI;
extern G__linked_taginfo G__EmrDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__EmrDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__EmrDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__EmrDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__EmrDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__EmrDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__EmrDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__EmrDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__EmrDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__EmrDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__EmrDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__EmrDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__EmrDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__EmrDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__EmrDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__EmrDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__EmrDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__EmrDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__EmrDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__EmrDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__EmrDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__EmrDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__EmrDictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__EmrDictLN_EdbSegP;
extern G__linked_taginfo G__EmrDictLN_EdbVertex;
extern G__linked_taginfo G__EmrDictLN_EdbTrackP;
extern G__linked_taginfo G__EmrDictLN_EdbEmrIO;
extern G__linked_taginfo G__EmrDictLN_EdbEmrFileAccess;

/* STUB derived class for protected member access */
