/********************************************************************
* ACQDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ACQDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern G__DLLEXPORT int G__cpp_dllrevACQDict();
extern G__DLLEXPORT void G__set_cpp_environmentACQDict();
extern G__DLLEXPORT void G__cpp_setup_tagtableACQDict();
extern G__DLLEXPORT void G__cpp_setup_inheritanceACQDict();
extern G__DLLEXPORT void G__cpp_setup_typetableACQDict();
extern G__DLLEXPORT void G__cpp_setup_memvarACQDict();
extern G__DLLEXPORT void G__cpp_setup_globalACQDict();
extern G__DLLEXPORT void G__cpp_setup_memfuncACQDict();
extern G__DLLEXPORT void G__cpp_setup_funcACQDict();
extern G__DLLEXPORT void G__cpp_setupACQDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "AcqStage1.h"
#include "AcqOdyssey.h"
#include "AcqMarksScanner.h"
#include "AcqTrackScanner.h"
#include "AcqTrackReconstructor.h"
#include "AcqSerialPlateChanger.h"
#include "AcqCOM.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ACQDictLN_TClass;
extern G__linked_taginfo G__ACQDictLN_TBuffer;
extern G__linked_taginfo G__ACQDictLN_TMemberInspector;
extern G__linked_taginfo G__ACQDictLN_TObject;
extern G__linked_taginfo G__ACQDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR;
extern G__linked_taginfo G__ACQDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ACQDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ACQDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__ACQDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__ACQDictLN_TClonesArray;
extern G__linked_taginfo G__ACQDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ACQDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ACQDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR;
extern G__linked_taginfo G__ACQDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__ACQDictLN_EdbAffine2D;
extern G__linked_taginfo G__ACQDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__ACQDictLN_TH1F;
extern G__linked_taginfo G__ACQDictLN_EdbMarksSet;
extern G__linked_taginfo G__ACQDictLN_EdbArea;
extern G__linked_taginfo G__ACQDictLN_AcqAxis;
extern G__linked_taginfo G__ACQDictLN_AcqLight;
extern G__linked_taginfo G__ACQDictLN_AcqStage1;
extern G__linked_taginfo G__ACQDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__ACQDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__ACQDictLN_EdbClustersBox;
extern G__linked_taginfo G__ACQDictLN_EdbFrame;
extern G__linked_taginfo G__ACQDictLN_EdbView;
extern G__linked_taginfo G__ACQDictLN_EdbImage;
extern G__linked_taginfo G__ACQDictLN_AcqOdyssey;
extern G__linked_taginfo G__ACQDictLN_AcqMarksScanner;
extern G__linked_taginfo G__ACQDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__ACQDictLN_EdbRun;
extern G__linked_taginfo G__ACQDictLN_AcqTrackScanner;
extern G__linked_taginfo G__ACQDictLN_AcqTrackReconstructor;
extern G__linked_taginfo G__ACQDictLN_AcqCOM;
extern G__linked_taginfo G__ACQDictLN_IdentifierS;
extern G__linked_taginfo G__ACQDictLN_TPlateS;
extern G__linked_taginfo G__ACQDictLN_AcqSerialPlateChanger;

/* STUB derived class for protected member access */
