/********************************************************************
* DataConversionDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error DataConversionDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern G__DLLEXPORT int G__cpp_dllrevDataConversionDict();
extern G__DLLEXPORT void G__set_cpp_environmentDataConversionDict();
extern G__DLLEXPORT void G__cpp_setup_tagtableDataConversionDict();
extern G__DLLEXPORT void G__cpp_setup_inheritanceDataConversionDict();
extern G__DLLEXPORT void G__cpp_setup_typetableDataConversionDict();
extern G__DLLEXPORT void G__cpp_setup_memvarDataConversionDict();
extern G__DLLEXPORT void G__cpp_setup_globalDataConversionDict();
extern G__DLLEXPORT void G__cpp_setup_memfuncDataConversionDict();
extern G__DLLEXPORT void G__cpp_setup_funcDataConversionDict();
extern G__DLLEXPORT void G__cpp_setupDataConversionDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "libDataConversion.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DataConversionDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR;
extern G__linked_taginfo G__DataConversionDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DataConversionDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DataConversionDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__DataConversionDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__DataConversionDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DataConversionDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DataConversionDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR;
extern G__linked_taginfo G__DataConversionDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR;

/* STUB derived class for protected member access */
