/********************************************************************
* EGADict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error EGADict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern G__DLLEXPORT int G__cpp_dllrevEGADict();
extern G__DLLEXPORT void G__set_cpp_environmentEGADict();
extern G__DLLEXPORT void G__cpp_setup_tagtableEGADict();
extern G__DLLEXPORT void G__cpp_setup_inheritanceEGADict();
extern G__DLLEXPORT void G__cpp_setup_typetableEGADict();
extern G__DLLEXPORT void G__cpp_setup_memvarEGADict();
extern G__DLLEXPORT void G__cpp_setup_globalEGADict();
extern G__DLLEXPORT void G__cpp_setup_memfuncEGADict();
extern G__DLLEXPORT void G__cpp_setup_funcEGADict();
extern G__DLLEXPORT void G__cpp_setupEGADict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "EdbGA.h"
#include "EdbIP.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EGADictLN_TClass;
extern G__linked_taginfo G__EGADictLN_TBuffer;
extern G__linked_taginfo G__EGADictLN_TMemberInspector;
extern G__linked_taginfo G__EGADictLN_TObject;
extern G__linked_taginfo G__EGADictLN_TNamed;
extern G__linked_taginfo G__EGADictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR;
extern G__linked_taginfo G__EGADictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EGADictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EGADictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__EGADictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__EGADictLN_TClonesArray;
extern G__linked_taginfo G__EGADictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EGADictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EGADictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR;
extern G__linked_taginfo G__EGADictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__EGADictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__EGADictLN_TFile;
extern G__linked_taginfo G__EGADictLN_TTree;
extern G__linked_taginfo G__EGADictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__EGADictLN_TCut;
extern G__linked_taginfo G__EGADictLN_TArrayF;
extern G__linked_taginfo G__EGADictLN_TH2F;
extern G__linked_taginfo G__EGADictLN_EdbPoint;
extern G__linked_taginfo G__EGADictLN_EdbPoint2D;
extern G__linked_taginfo G__EGADictLN_EdbPoint3D;
extern G__linked_taginfo G__EGADictLN_EdbCluster;
extern G__linked_taginfo G__EGADictLN_EdbFrame;
extern G__linked_taginfo G__EGADictLN_EdbView;
extern G__linked_taginfo G__EGADictLN_EdbRun;
extern G__linked_taginfo G__EGADictLN_TIndexCell;
extern G__linked_taginfo G__EGADictLN_EdbGA;
extern G__linked_taginfo G__EGADictLN_EdbImage;
extern G__linked_taginfo G__EGADictLN_EdbFIRF;
extern G__linked_taginfo G__EGADictLN_EdbClustP;
extern G__linked_taginfo G__EGADictLN_EdbIP;

/* STUB derived class for protected member access */
