/********************************************************************
* EIODict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error EIODict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern G__DLLEXPORT int G__cpp_dllrevEIODict();
extern G__DLLEXPORT void G__set_cpp_environmentEIODict();
extern G__DLLEXPORT void G__cpp_setup_tagtableEIODict();
extern G__DLLEXPORT void G__cpp_setup_inheritanceEIODict();
extern G__DLLEXPORT void G__cpp_setup_typetableEIODict();
extern G__DLLEXPORT void G__cpp_setup_memvarEIODict();
extern G__DLLEXPORT void G__cpp_setup_globalEIODict();
extern G__DLLEXPORT void G__cpp_setup_memfuncEIODict();
extern G__DLLEXPORT void G__cpp_setup_funcEIODict();
extern G__DLLEXPORT void G__cpp_setupEIODict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "EdbDataSet.h"
#include "EdbTraceBack.h"
#include "EdbRunAccess.h"
#include "EdbRunTracking.h"
#include "EdbRunParent.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EIODictLN_TClass;
extern G__linked_taginfo G__EIODictLN_TBuffer;
extern G__linked_taginfo G__EIODictLN_TMemberInspector;
extern G__linked_taginfo G__EIODictLN_TObject;
extern G__linked_taginfo G__EIODictLN_TNamed;
extern G__linked_taginfo G__EIODictLN_TString;
extern G__linked_taginfo G__EIODictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR;
extern G__linked_taginfo G__EIODictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EIODictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EIODictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__EIODictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__EIODictLN_TObjArray;
extern G__linked_taginfo G__EIODictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EIODictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EIODictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR;
extern G__linked_taginfo G__EIODictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__EIODictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__EIODictLN_TFile;
extern G__linked_taginfo G__EIODictLN_TCut;
extern G__linked_taginfo G__EIODictLN_EdbMask;
extern G__linked_taginfo G__EIODictLN_EdbAffine2D;
extern G__linked_taginfo G__EIODictLN_TTree;
extern G__linked_taginfo G__EIODictLN_TArrayI;
extern G__linked_taginfo G__EIODictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__EIODictLN_TArrayF;
extern G__linked_taginfo G__EIODictLN_TH2F;
extern G__linked_taginfo G__EIODictLN_EdbSegment;
extern G__linked_taginfo G__EIODictLN_EdbViewHeader;
extern G__linked_taginfo G__EIODictLN_EdbView;
extern G__linked_taginfo G__EIODictLN_EdbRun;
extern G__linked_taginfo G__EIODictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__EIODictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__EIODictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__EIODictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__EIODictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__EIODictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__EIODictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__EIODictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__EIODictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__EIODictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__EIODictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__EIODictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__EIODictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__EIODictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__EIODictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__EIODictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__EIODictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__EIODictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__EIODictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__EIODictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__EIODictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__EIODictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__EIODictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__EIODictLN_EdbSegP;
extern G__linked_taginfo G__EIODictLN_TIndexCell;
extern G__linked_taginfo G__EIODictLN_EdbTrackP;
extern G__linked_taginfo G__EIODictLN_EdbPattern;
extern G__linked_taginfo G__EIODictLN_EdbPatternsVolume;
extern G__linked_taginfo G__EIODictLN_EdbH2;
extern G__linked_taginfo G__EIODictLN_EdbLayer;
extern G__linked_taginfo G__EIODictLN_EdbScanCond;
extern G__linked_taginfo G__EIODictLN_EdbSegCouple;
extern G__linked_taginfo G__EIODictLN_TIndex2;
extern G__linked_taginfo G__EIODictLN_EdbPVRec;
extern G__linked_taginfo G__EIODictLN_EdbSegmentCut;
extern G__linked_taginfo G__EIODictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__EIODictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__EIODictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__EIODictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__EIODictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__EIODictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__EIODictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__EIODictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__EIODictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__EIODictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__EIODictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__EIODictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__EIODictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__EIODictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__EIODictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__EIODictLN_EdbDataPiece;
extern G__linked_taginfo G__EIODictLN_EdbDataSet;
extern G__linked_taginfo G__EIODictLN_EdbDataProc;
extern G__linked_taginfo G__EIODictLN_EdbTraceBack;
extern G__linked_taginfo G__EIODictLN_EdbRunAccess;
extern G__linked_taginfo G__EIODictLN_EdbPlateP;
extern G__linked_taginfo G__EIODictLN_EdbRunTracking;
extern G__linked_taginfo G__EIODictLN_EdbRunParent;

/* STUB derived class for protected member access */
