//
// File generated by C:\root_v5.34.26\bin\rootcint.EXE at Fri Sep 04 22:31:15 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME EphysDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "EphysDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void EdbPhysics_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_EdbPhysics(void *p = 0);
   static void *newArray_EdbPhysics(Long_t size, void *p);
   static void delete_EdbPhysics(void *p);
   static void deleteArray_EdbPhysics(void *p);
   static void destruct_EdbPhysics(void *p);
   static void streamer_EdbPhysics(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::EdbPhysics*)
   {
      ::EdbPhysics *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::EdbPhysics >(0);
      static ::ROOT::TGenericClassInfo 
         instance("EdbPhysics", ::EdbPhysics::Class_Version(), "./EdbPhys.h", 15,
                  typeid(::EdbPhysics), ::ROOT::DefineBehavior(ptr, ptr),
                  &::EdbPhysics::Dictionary, isa_proxy, 0,
                  sizeof(::EdbPhysics) );
      instance.SetNew(&new_EdbPhysics);
      instance.SetNewArray(&newArray_EdbPhysics);
      instance.SetDelete(&delete_EdbPhysics);
      instance.SetDeleteArray(&deleteArray_EdbPhysics);
      instance.SetDestructor(&destruct_EdbPhysics);
      instance.SetStreamerFunc(&streamer_EdbPhysics);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::EdbPhysics*)
   {
      return GenerateInitInstanceLocal((::EdbPhysics*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::EdbPhysics*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr EdbPhysics::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *EdbPhysics::Class_Name()
{
   return "EdbPhysics";
}

//______________________________________________________________________________
const char *EdbPhysics::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::EdbPhysics*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int EdbPhysics::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::EdbPhysics*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void EdbPhysics::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::EdbPhysics*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *EdbPhysics::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::EdbPhysics*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void EdbPhysics::Streamer(TBuffer &R__b)
{
   // Stream an object of class EdbPhysics.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b.CheckByteCount(R__s, R__c, EdbPhysics::IsA());
   } else {
      R__c = R__b.WriteVersion(EdbPhysics::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void EdbPhysics::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class EdbPhysics.
      typedef ::EdbPhysics msvc_bug_workaround;
      TClass *R__cl = msvc_bug_workaround::IsA();
      if (R__cl || R__insp.IsA()) { }
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_EdbPhysics(void *p) {
      return  p ? new(p) ::EdbPhysics : new ::EdbPhysics;
   }
   static void *newArray_EdbPhysics(Long_t nElements, void *p) {
      return p ? new(p) ::EdbPhysics[nElements] : new ::EdbPhysics[nElements];
   }
   // Wrapper around operator delete
   static void delete_EdbPhysics(void *p) {
      delete ((::EdbPhysics*)p);
   }
   static void deleteArray_EdbPhysics(void *p) {
      delete [] ((::EdbPhysics*)p);
   }
   static void destruct_EdbPhysics(void *p) {
      typedef ::EdbPhysics current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_EdbPhysics(TBuffer &buf, void *obj) {
      ((::EdbPhysics*)obj)->::EdbPhysics::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::EdbPhysics

/********************************************************
* EphysDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtableEphysDict();

extern "C" void G__set_cpp_environmentEphysDict() {
  G__add_ipath(".");
  G__add_ipath("..\\..\\include");
  G__cpp_reset_tagtableEphysDict();
}
#include <new>
extern "C" int G__cpp_dllrevEphysDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* EdbPhysics */
static int G__EphysDict_267_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   EdbPhysics* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new EdbPhysics[n];
     } else {
       p = new((void*) gvp) EdbPhysics[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new EdbPhysics;
     } else {
       p = new((void*) gvp) EdbPhysics;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__EphysDictLN_EdbPhysics));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EphysDict_267_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) EdbPhysics::kX0_Pb());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EphysDict_267_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) EdbPhysics::kX0_Em());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EphysDict_267_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) EdbPhysics::kX0_Cell());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EphysDict_267_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) EdbPhysics::ThetaMCS((float) G__double(libp->para[0]), (float) G__double(libp->para[1])
, (float) G__double(libp->para[2]), (float) G__double(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EphysDict_267_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) EdbPhysics::ThetaMS2((float) G__double(libp->para[0]), (float) G__double(libp->para[1])
, (float) G__double(libp->para[2]), (float) G__double(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EphysDict_267_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) EdbPhysics::ThetaPb2((float) G__double(libp->para[0]), (float) G__double(libp->para[1])
, (float) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EphysDict_267_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) EdbPhysics::DeAveragePb((float) G__double(libp->para[0]), (float) G__double(libp->para[1])
, (float) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EphysDict_267_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      EdbPhysics::DeAveragePbFastSet((float) G__double(libp->para[0]), (float) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EphysDict_267_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) EdbPhysics::DeAveragePbFast((float) G__double(libp->para[0]), (float) G__double(libp->para[1])
, (float) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EphysDict_267_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) EdbPhysics::DeLandauPb((float) G__double(libp->para[0]), (float) G__double(libp->para[1])
, (float) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EphysDict_267_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) EdbPhysics::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EphysDict_267_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EdbPhysics::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EphysDict_267_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) EdbPhysics::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EphysDict_267_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      EdbPhysics::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EphysDict_267_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdbPhysics*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EphysDict_267_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EdbPhysics::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EphysDict_267_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) EdbPhysics::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EphysDict_267_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EdbPhysics::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EphysDict_267_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) EdbPhysics::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__EphysDict_267_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   EdbPhysics* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new EdbPhysics(*(EdbPhysics*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__EphysDictLN_EdbPhysics));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef EdbPhysics G__TEdbPhysics;
static int G__EphysDict_267_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (EdbPhysics*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((EdbPhysics*) (soff+(sizeof(EdbPhysics)*i)))->~G__TEdbPhysics();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (EdbPhysics*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((EdbPhysics*) (soff))->~G__TEdbPhysics();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__EphysDict_267_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   EdbPhysics* dest = (EdbPhysics*) G__getstructoffset();
   *dest = *(EdbPhysics*) libp->para[0].ref;
   const EdbPhysics& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* EdbPhysics */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncEphysDict {
 public:
  G__Sizep2memfuncEphysDict(): p(&G__Sizep2memfuncEphysDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncEphysDict::*p)();
};

size_t G__get_sizep2memfuncEphysDict()
{
  G__Sizep2memfuncEphysDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceEphysDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__EphysDictLN_EdbPhysics))) {
     EdbPhysics *G__Lderived;
     G__Lderived=(EdbPhysics*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EphysDictLN_EdbPhysics),G__get_linked_tagnum(&G__EphysDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableEphysDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("iterator<iterator_traits<string::iterator>::iterator_category,iterator_traits<string::iterator>::value_type,iterator_traits<string::iterator>::difference_type,iterator_traits<string::iterator>::pointer,iterator_traits<string::iterator>::reference>",117,G__get_linked_tagnum(&G__EphysDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,char>",117,G__get_linked_tagnum(&G__EphysDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,char,long>",117,G__get_linked_tagnum(&G__EphysDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,char,long,char*>",117,G__get_linked_tagnum(&G__EphysDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<string::const_iterator>::iterator_category,iterator_traits<string::const_iterator>::value_type,iterator_traits<string::const_iterator>::difference_type,iterator_traits<string::const_iterator>::pointer,iterator_traits<string::const_iterator>::reference>",117,G__get_linked_tagnum(&G__EphysDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__EphysDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__EphysDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EphysDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EphysDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::iterator_category,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::value_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::difference_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::pointer,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::reference>",117,G__get_linked_tagnum(&G__EphysDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__EphysDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long>",117,G__get_linked_tagnum(&G__EphysDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long,ROOT::TSchemaHelper*>",117,G__get_linked_tagnum(&G__EphysDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EphysDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR),0,G__get_linked_tagnum(&G__EphysDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::iterator_category,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::value_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::difference_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::pointer,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::reference>",117,G__get_linked_tagnum(&G__EphysDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__EphysDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__EphysDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EphysDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EphysDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::iterator_category,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::value_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::difference_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::pointer,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::reference>",117,G__get_linked_tagnum(&G__EphysDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TVirtualArray*>",117,G__get_linked_tagnum(&G__EphysDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TVirtualArray*,long>",117,G__get_linked_tagnum(&G__EphysDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TVirtualArray*,long,TVirtualArray**>",117,G__get_linked_tagnum(&G__EphysDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EphysDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR),0,G__get_linked_tagnum(&G__EphysDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::iterator_category,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::value_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::difference_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::pointer,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::reference>",117,G__get_linked_tagnum(&G__EphysDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* EdbPhysics */
static void G__setup_memvarEdbPhysics(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__EphysDictLN_EdbPhysics));
   { EdbPhysics *p; p=(EdbPhysics*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EphysDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarEphysDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncEdbPhysics(void) {
   /* EdbPhysics */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__EphysDictLN_EdbPhysics));
   G__memfunc_setup("EdbPhysics",1006,G__EphysDict_267_0_1, 105, G__get_linked_tagnum(&G__EphysDictLN_EdbPhysics), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("kX0_Pb",516,G__EphysDict_267_0_2, 102, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (float (*)())(&EdbPhysics::kX0_Pb) ), 0);
   G__memfunc_setup("kX0_Em",516,G__EphysDict_267_0_3, 102, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (float (*)())(&EdbPhysics::kX0_Em) ), 0);
   G__memfunc_setup("kX0_Cell",722,G__EphysDict_267_0_4, 102, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (float (*)())(&EdbPhysics::kX0_Cell) ), 0);
   G__memfunc_setup("ThetaMCS",729,G__EphysDict_267_0_5, 100, -1, -1, 0, 4, 3, 1, 0, 
"f - - 0 - p f - - 0 - mass "
"f - - 0 - dx f - - 0 - x0", (char*)NULL, (void*) G__func2void( (double (*)(float, float, float, float))(&EdbPhysics::ThetaMCS) ), 0);
   G__memfunc_setup("ThetaMS2",712,G__EphysDict_267_0_6, 100, -1, -1, 0, 4, 3, 1, 0, 
"f - - 0 - p f - - 0 - mass "
"f - - 0 - dx f - - 0 - X0", (char*)NULL, (void*) G__func2void( (double (*)(float, float, float, float))(&EdbPhysics::ThetaMS2) ), 0);
   G__memfunc_setup("ThetaPb2",730,G__EphysDict_267_0_7, 100, -1, -1, 0, 3, 3, 1, 0, 
"f - - 0 - p f - - 0 - mass "
"f - - 0 - dx", (char*)NULL, (void*) G__func2void( (double (*)(float, float, float))(&EdbPhysics::ThetaPb2) ), 0);
   G__memfunc_setup("DeAveragePb",1046,G__EphysDict_267_0_8, 100, -1, -1, 0, 3, 3, 1, 0, 
"f - - 0 - p f - - 0 - mass "
"f - - 0 - dx", (char*)NULL, (void*) G__func2void( (double (*)(float, float, float))(&EdbPhysics::DeAveragePb) ), 0);
   G__memfunc_setup("DeAveragePbFastSet",1744,G__EphysDict_267_0_9, 121, -1, -1, 0, 2, 3, 1, 0, 
"f - - 0 - p f - - 0 - mass", (char*)NULL, (void*) G__func2void( (void (*)(float, float))(&EdbPhysics::DeAveragePbFastSet) ), 0);
   G__memfunc_setup("DeAveragePbFast",1444,G__EphysDict_267_0_10, 100, -1, -1, 0, 3, 3, 1, 0, 
"f - - 0 - p f - - 0 - mass "
"f - - 0 - dx", (char*)NULL, (void*) G__func2void( (double (*)(float, float, float))(&EdbPhysics::DeAveragePbFast) ), 0);
   G__memfunc_setup("DeLandauPb",944,G__EphysDict_267_0_11, 100, -1, -1, 0, 3, 3, 1, 0, 
"f - - 0 - p f - - 0 - mass "
"f - - 0 - dx", (char*)NULL, (void*) G__func2void( (double (*)(float, float, float))(&EdbPhysics::DeLandauPb) ), 0);
   G__memfunc_setup("Class",502,G__EphysDict_267_0_12, 85, G__get_linked_tagnum(&G__EphysDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&EdbPhysics::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__EphysDict_267_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EdbPhysics::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__EphysDict_267_0_14, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&EdbPhysics::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__EphysDict_267_0_15, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&EdbPhysics::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__EphysDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__EphysDict_267_0_19, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__EphysDict_267_0_20, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EdbPhysics::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__EphysDict_267_0_21, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&EdbPhysics::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__EphysDict_267_0_22, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EdbPhysics::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__EphysDict_267_0_23, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&EdbPhysics::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("EdbPhysics", 1006, G__EphysDict_267_0_24, (int) ('i'), G__get_linked_tagnum(&G__EphysDictLN_EdbPhysics), -1, 0, 1, 1, 1, 0, "u 'EdbPhysics' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~EdbPhysics", 1132, G__EphysDict_267_0_25, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__EphysDict_267_0_26, (int) ('u'), G__get_linked_tagnum(&G__EphysDictLN_EdbPhysics), -1, 1, 1, 1, 1, 0, "u 'EdbPhysics' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncEphysDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalEphysDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcEphysDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__EphysDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__EphysDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__EphysDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__EphysDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__EphysDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR = { "iterator<random_access_iterator_tag,char,long,char*,char&>" , 115 , -1 };
G__linked_taginfo G__EphysDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__EphysDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EphysDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR = { "iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long,ROOT::TSchemaHelper*,ROOT::TSchemaHelper&>" , 115 , -1 };
G__linked_taginfo G__EphysDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>" , 99 , -1 };
G__linked_taginfo G__EphysDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__EphysDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EphysDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR = { "iterator<random_access_iterator_tag,TVirtualArray*,long,TVirtualArray**,TVirtualArray*&>" , 115 , -1 };
G__linked_taginfo G__EphysDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>" , 99 , -1 };
G__linked_taginfo G__EphysDictLN_EdbPhysics = { "EdbPhysics" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableEphysDict() {
  G__EphysDictLN_TClass.tagnum = -1 ;
  G__EphysDictLN_TBuffer.tagnum = -1 ;
  G__EphysDictLN_TMemberInspector.tagnum = -1 ;
  G__EphysDictLN_TObject.tagnum = -1 ;
  G__EphysDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR.tagnum = -1 ;
  G__EphysDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__EphysDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EphysDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR.tagnum = -1 ;
  G__EphysDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR.tagnum = -1 ;
  G__EphysDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__EphysDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EphysDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR.tagnum = -1 ;
  G__EphysDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR.tagnum = -1 ;
  G__EphysDictLN_EdbPhysics.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableEphysDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__EphysDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__EphysDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__EphysDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__EphysDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__EphysDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR);
   G__get_linked_tagnum_fwd(&G__EphysDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__EphysDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EphysDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR);
   G__get_linked_tagnum_fwd(&G__EphysDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR);
   G__get_linked_tagnum_fwd(&G__EphysDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__EphysDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EphysDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR);
   G__get_linked_tagnum_fwd(&G__EphysDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__EphysDictLN_EdbPhysics),sizeof(EdbPhysics),-1,29952,"some physics",G__setup_memvarEdbPhysics,G__setup_memfuncEdbPhysics);
}
extern "C" void G__cpp_setupEphysDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupEphysDict()");
  G__set_cpp_environmentEphysDict();
  G__cpp_setup_tagtableEphysDict();

  G__cpp_setup_inheritanceEphysDict();

  G__cpp_setup_typetableEphysDict();

  G__cpp_setup_memvarEphysDict();

  G__cpp_setup_memfuncEphysDict();
  G__cpp_setup_globalEphysDict();
  G__cpp_setup_funcEphysDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncEphysDict();
  return;
}
class G__cpp_setup_initEphysDict {
  public:
    G__cpp_setup_initEphysDict() { G__add_setup_func("EphysDict",(G__incsetup)(&G__cpp_setupEphysDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initEphysDict() { G__remove_setup_func("EphysDict"); }
};
G__cpp_setup_initEphysDict G__cpp_setup_initializerEphysDict;

