/********************************************************************
* EphysDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error EphysDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern G__DLLEXPORT int G__cpp_dllrevEphysDict();
extern G__DLLEXPORT void G__set_cpp_environmentEphysDict();
extern G__DLLEXPORT void G__cpp_setup_tagtableEphysDict();
extern G__DLLEXPORT void G__cpp_setup_inheritanceEphysDict();
extern G__DLLEXPORT void G__cpp_setup_typetableEphysDict();
extern G__DLLEXPORT void G__cpp_setup_memvarEphysDict();
extern G__DLLEXPORT void G__cpp_setup_globalEphysDict();
extern G__DLLEXPORT void G__cpp_setup_memfuncEphysDict();
extern G__DLLEXPORT void G__cpp_setup_funcEphysDict();
extern G__DLLEXPORT void G__cpp_setupEphysDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "EdbPhys.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EphysDictLN_TClass;
extern G__linked_taginfo G__EphysDictLN_TBuffer;
extern G__linked_taginfo G__EphysDictLN_TMemberInspector;
extern G__linked_taginfo G__EphysDictLN_TObject;
extern G__linked_taginfo G__EphysDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR;
extern G__linked_taginfo G__EphysDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EphysDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EphysDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__EphysDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__EphysDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EphysDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EphysDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR;
extern G__linked_taginfo G__EphysDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__EphysDictLN_EdbPhysics;

/* STUB derived class for protected member access */
