/********************************************************************
* EGraphToolDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error EGraphToolDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern G__DLLEXPORT int G__cpp_dllrevEGraphToolDict();
extern G__DLLEXPORT void G__set_cpp_environmentEGraphToolDict();
extern G__DLLEXPORT void G__cpp_setup_tagtableEGraphToolDict();
extern G__DLLEXPORT void G__cpp_setup_inheritanceEGraphToolDict();
extern G__DLLEXPORT void G__cpp_setup_typetableEGraphToolDict();
extern G__DLLEXPORT void G__cpp_setup_memvarEGraphToolDict();
extern G__DLLEXPORT void G__cpp_setup_globalEGraphToolDict();
extern G__DLLEXPORT void G__cpp_setup_memfuncEGraphToolDict();
extern G__DLLEXPORT void G__cpp_setup_funcEGraphToolDict();
extern G__DLLEXPORT void G__cpp_setupEGraphToolDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "EGraphTool.h"
#include "EGraphRec.h"
#include "EGraphRecProc.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EGraphToolDictLN_TClass;
extern G__linked_taginfo G__EGraphToolDictLN_TBuffer;
extern G__linked_taginfo G__EGraphToolDictLN_TMemberInspector;
extern G__linked_taginfo G__EGraphToolDictLN_TObject;
extern G__linked_taginfo G__EGraphToolDictLN_TString;
extern G__linked_taginfo G__EGraphToolDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR;
extern G__linked_taginfo G__EGraphToolDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EGraphToolDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EGraphToolDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__EGraphToolDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__EGraphToolDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EGraphToolDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EGraphToolDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR;
extern G__linked_taginfo G__EGraphToolDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__EGraphToolDictLN_TQObject;
extern G__linked_taginfo G__EGraphToolDictLN_TGWindow;
extern G__linked_taginfo G__EGraphToolDictLN_TGObject;
extern G__linked_taginfo G__EGraphToolDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__EGraphToolDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__EGraphToolDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EGraphToolDictLN_iteratorlErandom_access_iterator_tagcOpairlEunsignedsPintcOintgRcOlongcOpairlEunsignedsPintcOintgRmUcOpairlEunsignedsPintcOintgRaNgR;
extern G__linked_taginfo G__EGraphToolDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__EGraphToolDictLN_TGFrame;
extern G__linked_taginfo G__EGraphToolDictLN_TGCompositeFrame;
extern G__linked_taginfo G__EGraphToolDictLN_TGLayoutHints;
extern G__linked_taginfo G__EGraphToolDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__EGraphToolDictLN_TGTextButton;
extern G__linked_taginfo G__EGraphToolDictLN_TGVerticalFrame;
extern G__linked_taginfo G__EGraphToolDictLN_TGMainFrame;
extern G__linked_taginfo G__EGraphToolDictLN_TGToolBar;
extern G__linked_taginfo G__EGraphToolDictLN_TGPopupMenu;
extern G__linked_taginfo G__EGraphToolDictLN_TFile;
extern G__linked_taginfo G__EGraphToolDictLN_TTree;
extern G__linked_taginfo G__EGraphToolDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__EGraphToolDictLN_TGCheckButton;
extern G__linked_taginfo G__EGraphToolDictLN_TGNumberEntry;
extern G__linked_taginfo G__EGraphToolDictLN_EdbView;
extern G__linked_taginfo G__EGraphToolDictLN_TThread;
extern G__linked_taginfo G__EGraphToolDictLN_EdbScanProc;
extern G__linked_taginfo G__EGraphToolDictLN_EdbScanSet;
extern G__linked_taginfo G__EGraphToolDictLN_EdbScanCond;
extern G__linked_taginfo G__EGraphToolDictLN_EdbVertexRec;
extern G__linked_taginfo G__EGraphToolDictLN_EdbPVRec;
extern G__linked_taginfo G__EGraphToolDictLN_ProcBrick_t;
extern G__linked_taginfo G__EGraphToolDictLN_ProcId_t;
extern G__linked_taginfo G__EGraphToolDictLN_VertexRecOpt_t;
extern G__linked_taginfo G__EGraphToolDictLN_EGraphRecProc;
extern G__linked_taginfo G__EGraphToolDictLN_TGTab;
extern G__linked_taginfo G__EGraphToolDictLN_TGTextView;
extern G__linked_taginfo G__EGraphToolDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__EGraphToolDictLN_TGLSAViewer;
extern G__linked_taginfo G__EGraphToolDictLN_EdbPattern;
extern G__linked_taginfo G__EGraphToolDictLN_EdbDisplay;
extern G__linked_taginfo G__EGraphToolDictLN_EGraphRec;
extern G__linked_taginfo G__EGraphToolDictLN_EGraphTool;

/* STUB derived class for protected member access */
