/********************************************************************
* EGACint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error EGACint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableEGACint();
extern void G__cpp_setup_inheritanceEGACint();
extern void G__cpp_setup_typetableEGACint();
extern void G__cpp_setup_memvarEGACint();
extern void G__cpp_setup_globalEGACint();
extern void G__cpp_setup_memfuncEGACint();
extern void G__cpp_setup_funcEGACint();
extern void G__set_cpp_environmentEGACint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "EdbGA.h"
#include "EdbIP.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EGACintLN_TClass;
extern G__linked_taginfo G__EGACintLN_TBuffer;
extern G__linked_taginfo G__EGACintLN_TMemberInspector;
extern G__linked_taginfo G__EGACintLN_TObject;
extern G__linked_taginfo G__EGACintLN_TNamed;
extern G__linked_taginfo G__EGACintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EGACintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EGACintLN_TClonesArray;
extern G__linked_taginfo G__EGACintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EGACintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EGACintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__EGACintLN_TFile;
extern G__linked_taginfo G__EGACintLN_TTree;
extern G__linked_taginfo G__EGACintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__EGACintLN_TCut;
extern G__linked_taginfo G__EGACintLN_TArrayF;
extern G__linked_taginfo G__EGACintLN_TH2F;
extern G__linked_taginfo G__EGACintLN_EdbPoint;
extern G__linked_taginfo G__EGACintLN_EdbPoint2D;
extern G__linked_taginfo G__EGACintLN_EdbPoint3D;
extern G__linked_taginfo G__EGACintLN_EdbCluster;
extern G__linked_taginfo G__EGACintLN_EdbFrame;
extern G__linked_taginfo G__EGACintLN_EdbView;
extern G__linked_taginfo G__EGACintLN_EdbRun;
extern G__linked_taginfo G__EGACintLN_TIndexCell;
extern G__linked_taginfo G__EGACintLN_EdbGA;
extern G__linked_taginfo G__EGACintLN_EdbImage;
extern G__linked_taginfo G__EGACintLN_EdbFIRF;
extern G__linked_taginfo G__EGACintLN_EdbClustP;
extern G__linked_taginfo G__EGACintLN_EdbIP;

/* STUB derived class for protected member access */
