/********************************************************************
* AlignmentCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error AlignmentCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableAlignmentCint();
extern void G__cpp_setup_inheritanceAlignmentCint();
extern void G__cpp_setup_typetableAlignmentCint();
extern void G__cpp_setup_memvarAlignmentCint();
extern void G__cpp_setup_globalAlignmentCint();
extern void G__cpp_setup_memfuncAlignmentCint();
extern void G__cpp_setup_funcAlignmentCint();
extern void G__set_cpp_environmentAlignmentCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "EdbPatCell2.h"
#include "EdbPositionAlignment.h"
#include "EdbAlignmentMap.h"
#include "EdbPeakProb.h"
#include "EdbTestAl.h"
#include "EdbAlignmentV.h"
#include "EdbPlateAlignment.h"
#include "EdbLinking.h"
#include "EdbCorrectionMapper.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__AlignmentCintLN_TClass;
extern G__linked_taginfo G__AlignmentCintLN_TBuffer;
extern G__linked_taginfo G__AlignmentCintLN_TMemberInspector;
extern G__linked_taginfo G__AlignmentCintLN_TObject;
extern G__linked_taginfo G__AlignmentCintLN_TString;
extern G__linked_taginfo G__AlignmentCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__AlignmentCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AlignmentCintLN_TObjArray;
extern G__linked_taginfo G__AlignmentCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__AlignmentCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AlignmentCintLN_EdbAffine2D;
extern G__linked_taginfo G__AlignmentCintLN_TArrayF;
extern G__linked_taginfo G__AlignmentCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__AlignmentCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__AlignmentCintLN_TH1I;
extern G__linked_taginfo G__AlignmentCintLN_TH1F;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__AlignmentCintLN_TH2F;
extern G__linked_taginfo G__AlignmentCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__AlignmentCintLN_EdbH1;
extern G__linked_taginfo G__AlignmentCintLN_EdbH2;
extern G__linked_taginfo G__AlignmentCintLN_EdbPeak2;
extern G__linked_taginfo G__AlignmentCintLN_EdbCell2;
extern G__linked_taginfo G__AlignmentCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__AlignmentCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__AlignmentCintLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__AlignmentCintLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__AlignmentCintLN_EdbID;
extern G__linked_taginfo G__AlignmentCintLN_EdbSegP;
extern G__linked_taginfo G__AlignmentCintLN_EdbSegCorr;
extern G__linked_taginfo G__AlignmentCintLN_EdbLayer;
extern G__linked_taginfo G__AlignmentCintLN_EdbCorrectionMap;
extern G__linked_taginfo G__AlignmentCintLN_TTree;
extern G__linked_taginfo G__AlignmentCintLN_TFile;
extern G__linked_taginfo G__AlignmentCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__AlignmentCintLN_TEventList;
extern G__linked_taginfo G__AlignmentCintLN_TCut;
extern G__linked_taginfo G__AlignmentCintLN_EdbPattern;
extern G__linked_taginfo G__AlignmentCintLN_EdbPatCell2;
extern G__linked_taginfo G__AlignmentCintLN_EdbPlateP;
extern G__linked_taginfo G__AlignmentCintLN_EdbPositionAlignment;
extern G__linked_taginfo G__AlignmentCintLN_TGraph2D;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__AlignmentCintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__AlignmentCintLN_TVector3;
extern G__linked_taginfo G__AlignmentCintLN_TEnv;
extern G__linked_taginfo G__AlignmentCintLN_EdbAlignmentMap;
extern G__linked_taginfo G__AlignmentCintLN_EdbPeakProb;
extern G__linked_taginfo G__AlignmentCintLN_TNtuple;
extern G__linked_taginfo G__AlignmentCintLN_EdbTestAl;
extern G__linked_taginfo G__AlignmentCintLN_EdbAlignmentV;
extern G__linked_taginfo G__AlignmentCintLN_EdbPlateAlignment;
extern G__linked_taginfo G__AlignmentCintLN_EdbScanCond;
extern G__linked_taginfo G__AlignmentCintLN_EdbSEQ;
extern G__linked_taginfo G__AlignmentCintLN_EdbLinking;
extern G__linked_taginfo G__AlignmentCintLN_EdbLinkingcLcLRemoveDoublets;
extern G__linked_taginfo G__AlignmentCintLN_TCanvas;
extern G__linked_taginfo G__AlignmentCintLN_EdbCorrectionBin;
extern G__linked_taginfo G__AlignmentCintLN_EdbCorrectionMapper;

/* STUB derived class for protected member access */
