/********************************************************************
* EbaseCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error EbaseCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableEbaseCint();
extern void G__cpp_setup_inheritanceEbaseCint();
extern void G__cpp_setup_typetableEbaseCint();
extern void G__cpp_setup_memvarEbaseCint();
extern void G__cpp_setup_globalEbaseCint();
extern void G__cpp_setup_memfuncEbaseCint();
extern void G__cpp_setup_funcEbaseCint();
extern void G__set_cpp_environmentEbaseCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "EdbSegCorr.h"
#include "EdbLayer.h"
#include "EdbScanCond.h"
#include "EdbBrick.h"
#include "EdbScanSet.h"
#include "EdbID.h"
#include "EdbSegP.h"
#include "EdbSigma.h"
#include "EdbSEQ.h"
#include "EdbCouplesTree.h"
#include "EdbSegCouple.h"
#include "EdbSegmentCut.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EbaseCintLN_TClass;
extern G__linked_taginfo G__EbaseCintLN_TBuffer;
extern G__linked_taginfo G__EbaseCintLN_TMemberInspector;
extern G__linked_taginfo G__EbaseCintLN_TObject;
extern G__linked_taginfo G__EbaseCintLN_TNamed;
extern G__linked_taginfo G__EbaseCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EbaseCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EbaseCintLN_TList;
extern G__linked_taginfo G__EbaseCintLN_TObjArray;
extern G__linked_taginfo G__EbaseCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EbaseCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EbaseCintLN_TArrayF;
extern G__linked_taginfo G__EbaseCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__EbaseCintLN_TRefArray;
extern G__linked_taginfo G__EbaseCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__EbaseCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__EbaseCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__EbaseCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__EbaseCintLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__EbaseCintLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__EbaseCintLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__EbaseCintLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__EbaseCintLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__EbaseCintLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__EbaseCintLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__EbaseCintLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__EbaseCintLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__EbaseCintLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__EbaseCintLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__EbaseCintLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__EbaseCintLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__EbaseCintLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__EbaseCintLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__EbaseCintLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__EbaseCintLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__EbaseCintLN_TH1F;
extern G__linked_taginfo G__EbaseCintLN_EdbAffine2D;
extern G__linked_taginfo G__EbaseCintLN_EdbPoint;
extern G__linked_taginfo G__EbaseCintLN_EdbPoint2D;
extern G__linked_taginfo G__EbaseCintLN_EdbAngle2D;
extern G__linked_taginfo G__EbaseCintLN_EdbTrack2D;
extern G__linked_taginfo G__EbaseCintLN_EdbID;
extern G__linked_taginfo G__EbaseCintLN_EdbSegP;
extern G__linked_taginfo G__EbaseCintLN_EdbSegCorr;
extern G__linked_taginfo G__EbaseCintLN_TF1;
extern G__linked_taginfo G__EbaseCintLN_EdbH1;
extern G__linked_taginfo G__EbaseCintLN_EdbH2;
extern G__linked_taginfo G__EbaseCintLN_EdbCell2;
extern G__linked_taginfo G__EbaseCintLN_EdbLayer;
extern G__linked_taginfo G__EbaseCintLN_EdbCorrectionMap;
extern G__linked_taginfo G__EbaseCintLN_EdbScanCond;
extern G__linked_taginfo G__EbaseCintLN_EdbPlateP;
extern G__linked_taginfo G__EbaseCintLN_EdbBrickP;
extern G__linked_taginfo G__EbaseCintLN_TIndexCell;
extern G__linked_taginfo G__EbaseCintLN_EdbScanSet;
extern G__linked_taginfo G__EbaseCintLN_EdbSigma;
extern G__linked_taginfo G__EbaseCintLN_TVector2;
extern G__linked_taginfo G__EbaseCintLN_TTree;
extern G__linked_taginfo G__EbaseCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__EbaseCintLN_TEventList;
extern G__linked_taginfo G__EbaseCintLN_TCut;
extern G__linked_taginfo G__EbaseCintLN_EdbPattern;
extern G__linked_taginfo G__EbaseCintLN_EdbSEQ;
extern G__linked_taginfo G__EbaseCintLN_EdbSegCouple;
extern G__linked_taginfo G__EbaseCintLN_EdbMask;
extern G__linked_taginfo G__EbaseCintLN_TIndex2;
extern G__linked_taginfo G__EbaseCintLN_EdbCouplesTree;
extern G__linked_taginfo G__EbaseCintLN_EdbSegmentCut;

/* STUB derived class for protected member access */
