/********************************************************************
* EdbCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error EdbCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableEdbCint();
extern void G__cpp_setup_inheritanceEdbCint();
extern void G__cpp_setup_typetableEdbCint();
extern void G__cpp_setup_memvarEdbCint();
extern void G__cpp_setup_globalEdbCint();
extern void G__cpp_setup_memfuncEdbCint();
extern void G__cpp_setup_funcEdbCint();
extern void G__set_cpp_environmentEdbCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "EdbLog.h"
#include "EdbCluster.h"
#include "EdbView.h"
#include "EdbRunHeader.h"
#include "EdbRun.h"
#include "EdbImage.h"
#include "EdbFrame.h"
#include "EdbSegment.h"
#include "EdbStage.h"
#include "EdbAffine.h"
#include "EdbFiducial.h"
#include "EdbVirtual.h"
#include "EdbPrediction.h"
#include "EdbOnline.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EdbCintLN_TClass;
extern G__linked_taginfo G__EdbCintLN_TBuffer;
extern G__linked_taginfo G__EdbCintLN_TMemberInspector;
extern G__linked_taginfo G__EdbCintLN_TObject;
extern G__linked_taginfo G__EdbCintLN_TNamed;
extern G__linked_taginfo G__EdbCintLN_TString;
extern G__linked_taginfo G__EdbCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EdbCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EdbCintLN_va_list;
extern G__linked_taginfo G__EdbCintLN_TList;
extern G__linked_taginfo G__EdbCintLN_TObjArray;
extern G__linked_taginfo G__EdbCintLN_TClonesArray;
extern G__linked_taginfo G__EdbCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EdbCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EdbCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__EdbCintLN_TTree;
extern G__linked_taginfo G__EdbCintLN_TFile;
extern G__linked_taginfo G__EdbCintLN_TArrayD;
extern G__linked_taginfo G__EdbCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__EdbCintLN_TNtuple;
extern G__linked_taginfo G__EdbCintLN_TH1F;
extern G__linked_taginfo G__EdbCintLN_TH2F;
extern G__linked_taginfo G__EdbCintLN_EdbAffine2D;
extern G__linked_taginfo G__EdbCintLN_EdbAffine3D;
extern G__linked_taginfo G__EdbCintLN_EdbPoint;
extern G__linked_taginfo G__EdbCintLN_EdbPoint2D;
extern G__linked_taginfo G__EdbCintLN_EdbPoint3D;
extern G__linked_taginfo G__EdbCintLN_EdbAngle2D;
extern G__linked_taginfo G__EdbCintLN_EdbTrack2D;
extern G__linked_taginfo G__EdbCintLN_EdbPointsBox2D;
extern G__linked_taginfo G__EdbCintLN_EdbPointsBox3D;
extern G__linked_taginfo G__EdbCintLN_EdbCluster;
extern G__linked_taginfo G__EdbCintLN_EdbClustersBox;
extern G__linked_taginfo G__EdbCintLN_TPolyMarker3D;
extern G__linked_taginfo G__EdbCintLN_TArrayF;
extern G__linked_taginfo G__EdbCintLN_EdbSeg3D;
extern G__linked_taginfo G__EdbCintLN_EdbSegment;
extern G__linked_taginfo G__EdbCintLN_EdbTrack;
extern G__linked_taginfo G__EdbCintLN_EdbFrame;
extern G__linked_taginfo G__EdbCintLN_EdbViewHeader;
extern G__linked_taginfo G__EdbCintLN_EdbView;
extern G__linked_taginfo G__EdbCintLN_TDatime;
extern G__linked_taginfo G__EdbCintLN_EdbCCD;
extern G__linked_taginfo G__EdbCintLN_EdbObjective;
extern G__linked_taginfo G__EdbCintLN_EdbStage;
extern G__linked_taginfo G__EdbCintLN_EdbMark;
extern G__linked_taginfo G__EdbCintLN_EdbMarksBox;
extern G__linked_taginfo G__EdbCintLN_EdbMarksSet;
extern G__linked_taginfo G__EdbCintLN_EdbArea;
extern G__linked_taginfo G__EdbCintLN_EdbPlate;
extern G__linked_taginfo G__EdbCintLN_EdbCamera;
extern G__linked_taginfo G__EdbCintLN_EdbRunHeader;
extern G__linked_taginfo G__EdbCintLN_TArrayC;
extern G__linked_taginfo G__EdbCintLN_EdbPredictionDC;
extern G__linked_taginfo G__EdbCintLN_EdbPredictionsBox;
extern G__linked_taginfo G__EdbCintLN_AlignmentParView;
extern G__linked_taginfo G__EdbCintLN_AlignmentParFrame;
extern G__linked_taginfo G__EdbCintLN_EdbRun;
extern G__linked_taginfo G__EdbCintLN_EdbImage;

/* STUB derived class for protected member access */
