/********************************************************************
* EIOCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error EIOCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableEIOCint();
extern void G__cpp_setup_inheritanceEIOCint();
extern void G__cpp_setup_typetableEIOCint();
extern void G__cpp_setup_memvarEIOCint();
extern void G__cpp_setup_globalEIOCint();
extern void G__cpp_setup_memfuncEIOCint();
extern void G__cpp_setup_funcEIOCint();
extern void G__set_cpp_environmentEIOCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "EdbDataSet.h"
#include "EdbTraceBack.h"
#include "EdbRunAccess.h"
#include "EdbRunTracking.h"
#include "EdbRunParent.h"
#include "EdbViewMap.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EIOCintLN_TClass;
extern G__linked_taginfo G__EIOCintLN_TBuffer;
extern G__linked_taginfo G__EIOCintLN_TMemberInspector;
extern G__linked_taginfo G__EIOCintLN_TObject;
extern G__linked_taginfo G__EIOCintLN_TNamed;
extern G__linked_taginfo G__EIOCintLN_TString;
extern G__linked_taginfo G__EIOCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EIOCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EIOCintLN_TObjArray;
extern G__linked_taginfo G__EIOCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EIOCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EIOCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__EIOCintLN_TFile;
extern G__linked_taginfo G__EIOCintLN_TCut;
extern G__linked_taginfo G__EIOCintLN_EdbMask;
extern G__linked_taginfo G__EIOCintLN_EdbAffine2D;
extern G__linked_taginfo G__EIOCintLN_TTree;
extern G__linked_taginfo G__EIOCintLN_TArrayI;
extern G__linked_taginfo G__EIOCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__EIOCintLN_TArrayF;
extern G__linked_taginfo G__EIOCintLN_TH2F;
extern G__linked_taginfo G__EIOCintLN_EdbSegment;
extern G__linked_taginfo G__EIOCintLN_EdbViewHeader;
extern G__linked_taginfo G__EIOCintLN_EdbView;
extern G__linked_taginfo G__EIOCintLN_AlignmentParView;
extern G__linked_taginfo G__EIOCintLN_AlignmentParFrame;
extern G__linked_taginfo G__EIOCintLN_EdbRun;
extern G__linked_taginfo G__EIOCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__EIOCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__EIOCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__EIOCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__EIOCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__EIOCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__EIOCintLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__EIOCintLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__EIOCintLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__EIOCintLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__EIOCintLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__EIOCintLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__EIOCintLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__EIOCintLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__EIOCintLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__EIOCintLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__EIOCintLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__EIOCintLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__EIOCintLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__EIOCintLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__EIOCintLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__EIOCintLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__EIOCintLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__EIOCintLN_EdbSegP;
extern G__linked_taginfo G__EIOCintLN_TIndexCell;
extern G__linked_taginfo G__EIOCintLN_EdbTrackP;
extern G__linked_taginfo G__EIOCintLN_EdbPattern;
extern G__linked_taginfo G__EIOCintLN_EdbPatternsVolume;
extern G__linked_taginfo G__EIOCintLN_TH2D;
extern G__linked_taginfo G__EIOCintLN_EdbH2;
extern G__linked_taginfo G__EIOCintLN_EdbLayer;
extern G__linked_taginfo G__EIOCintLN_EdbScanCond;
extern G__linked_taginfo G__EIOCintLN_EdbSegCouple;
extern G__linked_taginfo G__EIOCintLN_TIndex2;
extern G__linked_taginfo G__EIOCintLN_EdbPVRec;
extern G__linked_taginfo G__EIOCintLN_EdbSegmentCut;
extern G__linked_taginfo G__EIOCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__EIOCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__EIOCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__EIOCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__EIOCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__EIOCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__EIOCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__EIOCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__EIOCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__EIOCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__EIOCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__EIOCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__EIOCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__EIOCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__EIOCintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__EIOCintLN_EdbDataPiece;
extern G__linked_taginfo G__EIOCintLN_EdbDataSet;
extern G__linked_taginfo G__EIOCintLN_EdbDataProc;
extern G__linked_taginfo G__EIOCintLN_EdbTraceBack;
extern G__linked_taginfo G__EIOCintLN_EdbRunAccess;
extern G__linked_taginfo G__EIOCintLN_EdbPlateP;
extern G__linked_taginfo G__EIOCintLN_EdbRunTracking;
extern G__linked_taginfo G__EIOCintLN_EdbRunParent;
extern G__linked_taginfo G__EIOCintLN_AApv;
extern G__linked_taginfo G__EIOCintLN_AView;
extern G__linked_taginfo G__EIOCintLN_AArea;
extern G__linked_taginfo G__EIOCintLN_ARun;
extern G__linked_taginfo G__EIOCintLN_EdbViewMap;

/* STUB derived class for protected member access */
