/********************************************************************
* EmathCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error EmathCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableEmathCint();
extern void G__cpp_setup_inheritanceEmathCint();
extern void G__cpp_setup_typetableEmathCint();
extern void G__cpp_setup_memvarEmathCint();
extern void G__cpp_setup_globalEmathCint();
extern void G__cpp_setup_memfuncEmathCint();
extern void G__cpp_setup_funcEmathCint();
extern void G__set_cpp_environmentEmathCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TIndexCell.h"
#include "EdbMath.h"
#include "EdbCell2.h"
#include "EdbCell1.h"
#include "EdbMask.h"
#include "EdbCombGen.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EmathCintLN_TClass;
extern G__linked_taginfo G__EmathCintLN_TBuffer;
extern G__linked_taginfo G__EmathCintLN_TMemberInspector;
extern G__linked_taginfo G__EmathCintLN_TObject;
extern G__linked_taginfo G__EmathCintLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__EmathCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EmathCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EmathCintLN_TObjArray;
extern G__linked_taginfo G__EmathCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EmathCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EmathCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__EmathCintLN_TIndexCell;
extern G__linked_taginfo G__EmathCintLN_TIndexCellIter;
extern G__linked_taginfo G__EmathCintLN_TIndexCellIterV;
extern G__linked_taginfo G__EmathCintLN_TArray;
extern G__linked_taginfo G__EmathCintLN_TArrayI;
extern G__linked_taginfo G__EmathCintLN_TArrayD;
extern G__linked_taginfo G__EmathCintLN_TArrayC;
extern G__linked_taginfo G__EmathCintLN_TArrayF;
extern G__linked_taginfo G__EmathCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__EmathCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__EmathCintLN_TH1I;
extern G__linked_taginfo G__EmathCintLN_TH1F;
extern G__linked_taginfo G__EmathCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__EmathCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__EmathCintLN_TH2F;
extern G__linked_taginfo G__EmathCintLN_TH2D;
extern G__linked_taginfo G__EmathCintLN_EdbMath;
extern G__linked_taginfo G__EmathCintLN_TIndex2;
extern G__linked_taginfo G__EmathCintLN_EdbFilter2D;
extern G__linked_taginfo G__EmathCintLN_EdbH1;
extern G__linked_taginfo G__EmathCintLN_EdbCell1;
extern G__linked_taginfo G__EmathCintLN_EdbH2;
extern G__linked_taginfo G__EmathCintLN_EdbPeak2;
extern G__linked_taginfo G__EmathCintLN_EdbCell2;
extern G__linked_taginfo G__EmathCintLN_EdbMask;
extern G__linked_taginfo G__EmathCintLN_EdbCombGen;

/* STUB derived class for protected member access */
