/********************************************************************
* EMCCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error EMCCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableEMCCint();
extern void G__cpp_setup_inheritanceEMCCint();
extern void G__cpp_setup_typetableEMCCint();
extern void G__cpp_setup_memvarEMCCint();
extern void G__cpp_setup_globalEMCCint();
extern void G__cpp_setup_memfuncEMCCint();
extern void G__cpp_setup_funcEMCCint();
extern void G__set_cpp_environmentEMCCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "EdbPVGen.h"
#include "EdbBrickGen.h"
#include "EdbViewDef.h"
#include "EdbViewGen.h"
#include "EdbViewRec.h"
#include "EdbViewMatch.h"
#include "EdbDataStore.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EMCCintLN_TClass;
extern G__linked_taginfo G__EMCCintLN_TBuffer;
extern G__linked_taginfo G__EMCCintLN_TMemberInspector;
extern G__linked_taginfo G__EMCCintLN_TObject;
extern G__linked_taginfo G__EMCCintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__EMCCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EMCCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EMCCintLN_TObjArray;
extern G__linked_taginfo G__EMCCintLN_TClonesArray;
extern G__linked_taginfo G__EMCCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EMCCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EMCCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__EMCCintLN_TFile;
extern G__linked_taginfo G__EMCCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__EMCCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__EMCCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__EMCCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__EMCCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__EMCCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__EMCCintLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__EMCCintLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__EMCCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__EMCCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__EMCCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__EMCCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__EMCCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__EMCCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__EMCCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__EMCCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__EMCCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__EMCCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__EMCCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__EMCCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__EMCCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__EMCCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__EMCCintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__EMCCintLN_TGenPhaseSpace;
extern G__linked_taginfo G__EMCCintLN_TTree;
extern G__linked_taginfo G__EMCCintLN_TArrayI;
extern G__linked_taginfo G__EMCCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__EMCCintLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__EMCCintLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__EMCCintLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__EMCCintLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__EMCCintLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__EMCCintLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__EMCCintLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__EMCCintLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__EMCCintLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__EMCCintLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__EMCCintLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__EMCCintLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__EMCCintLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__EMCCintLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__EMCCintLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__EMCCintLN_EdbID;
extern G__linked_taginfo G__EMCCintLN_EdbSegP;
extern G__linked_taginfo G__EMCCintLN_EdbVertex;
extern G__linked_taginfo G__EMCCintLN_EdbTrackP;
extern G__linked_taginfo G__EMCCintLN_EdbPattern;
extern G__linked_taginfo G__EMCCintLN_EdbPatternsVolume;
extern G__linked_taginfo G__EMCCintLN_TArrayF;
extern G__linked_taginfo G__EMCCintLN_TF1;
extern G__linked_taginfo G__EMCCintLN_TH2;
extern G__linked_taginfo G__EMCCintLN_EdbCell2;
extern G__linked_taginfo G__EMCCintLN_EdbLayer;
extern G__linked_taginfo G__EMCCintLN_EdbScanCond;
extern G__linked_taginfo G__EMCCintLN_listlEVERTEXcLcLRelationmUcOallocatorlEVERTEXcLcLRelationmUgRsPgR;
extern G__linked_taginfo G__EMCCintLN_listlEVERTEXcLcLMassCmUcOallocatorlEVERTEXcLcLMassCmUgRsPgR;
extern G__linked_taginfo G__EMCCintLN_vectorlEVERTEXcLcLTrackmUcOallocatorlEVERTEXcLcLTrackmUgRsPgR;
extern G__linked_taginfo G__EMCCintLN_reverse_iteratorlEvectorlEVERTEXcLcLTrackmUcOallocatorlEVERTEXcLcLTrackmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EMCCintLN_EdbVertexRec;
extern G__linked_taginfo G__EMCCintLN_EdbPVGen;
extern G__linked_taginfo G__EMCCintLN_EdbBrickP;
extern G__linked_taginfo G__EMCCintLN_EdbBeamGen;
extern G__linked_taginfo G__EMCCintLN_EdbBrickGen;
extern G__linked_taginfo G__EMCCintLN_EdbViewDef;
extern G__linked_taginfo G__EMCCintLN_EdbCluster;
extern G__linked_taginfo G__EMCCintLN_EdbSegment;
extern G__linked_taginfo G__EMCCintLN_EdbView;
extern G__linked_taginfo G__EMCCintLN_EdbViewGen;
extern G__linked_taginfo G__EMCCintLN_EdbViewCell;
extern G__linked_taginfo G__EMCCintLN_EdbViewRec;
extern G__linked_taginfo G__EMCCintLN_TEnv;
extern G__linked_taginfo G__EMCCintLN_TNtuple;
extern G__linked_taginfo G__EMCCintLN_EdbClMatch;
extern G__linked_taginfo G__EMCCintLN_EdbViewMatch;
extern G__linked_taginfo G__EMCCintLN_EdbSegmentCut;
extern G__linked_taginfo G__EMCCintLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__EMCCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EMCCintLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__EMCCintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__EMCCintLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EMCCintLN_EdbMomentumEstimator;
extern G__linked_taginfo G__EMCCintLN_EdbDataStore;
extern G__linked_taginfo G__EMCCintLN_EdbDSRec;

/* STUB derived class for protected member access */
