/********************************************************************
* EmrCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error EmrCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableEmrCint();
extern void G__cpp_setup_inheritanceEmrCint();
extern void G__cpp_setup_typetableEmrCint();
extern void G__cpp_setup_memvarEmrCint();
extern void G__cpp_setup_globalEmrCint();
extern void G__cpp_setup_memfuncEmrCint();
extern void G__cpp_setup_funcEmrCint();
extern void G__set_cpp_environmentEmrCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "EdbEmrIO.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EmrCintLN_TClass;
extern G__linked_taginfo G__EmrCintLN_TBuffer;
extern G__linked_taginfo G__EmrCintLN_TMemberInspector;
extern G__linked_taginfo G__EmrCintLN_TObject;
extern G__linked_taginfo G__EmrCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EmrCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EmrCintLN_TObjArray;
extern G__linked_taginfo G__EmrCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EmrCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EmrCintLN_TArrayI;
extern G__linked_taginfo G__EmrCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__EmrCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__EmrCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__EmrCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__EmrCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__EmrCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__EmrCintLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__EmrCintLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__EmrCintLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__EmrCintLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__EmrCintLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__EmrCintLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__EmrCintLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__EmrCintLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__EmrCintLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__EmrCintLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__EmrCintLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__EmrCintLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__EmrCintLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__EmrCintLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__EmrCintLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__EmrCintLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__EmrCintLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__EmrCintLN_EdbSegP;
extern G__linked_taginfo G__EmrCintLN_EdbVertex;
extern G__linked_taginfo G__EmrCintLN_EdbTrackP;
extern G__linked_taginfo G__EmrCintLN_EdbEmrIO;
extern G__linked_taginfo G__EmrCintLN_EdbEmrFileAccess;

/* STUB derived class for protected member access */
