/********************************************************************
* EphysCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error EphysCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableEphysCint();
extern void G__cpp_setup_inheritanceEphysCint();
extern void G__cpp_setup_typetableEphysCint();
extern void G__cpp_setup_memvarEphysCint();
extern void G__cpp_setup_globalEphysCint();
extern void G__cpp_setup_memfuncEphysCint();
extern void G__cpp_setup_funcEphysCint();
extern void G__set_cpp_environmentEphysCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "EdbPhys.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EphysCintLN_TClass;
extern G__linked_taginfo G__EphysCintLN_TBuffer;
extern G__linked_taginfo G__EphysCintLN_TMemberInspector;
extern G__linked_taginfo G__EphysCintLN_TObject;
extern G__linked_taginfo G__EphysCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EphysCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EphysCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EphysCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EphysCintLN_EdbPhysics;

/* STUB derived class for protected member access */
