/********************************************************************
* ScanCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ScanCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableScanCint();
extern void G__cpp_setup_inheritanceScanCint();
extern void G__cpp_setup_typetableScanCint();
extern void G__cpp_setup_memvarScanCint();
extern void G__cpp_setup_globalScanCint();
extern void G__cpp_setup_memfuncScanCint();
extern void G__cpp_setup_funcScanCint();
extern void G__set_cpp_environmentScanCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "EdbScanClient.h"
#include "EdbScanProc.h"
#include "EdbProcPars.h"
#include "EdbScanTracking.h"
#include "EdbScanClientBase.h"
#include "EdbScanClientPav.h"
#include "EdbScanClientSysal.h"
#include "MessageManager.h"
#include "MessageReader.h"
#include "tinyxml.h"
#include "tinystr.h"
#include "tinyxmlerror.h"
#include "tinyxmlparser.h"
#include "PAVProtocol.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ScanCintLN_TClass;
extern G__linked_taginfo G__ScanCintLN_TBuffer;
extern G__linked_taginfo G__ScanCintLN_TMemberInspector;
extern G__linked_taginfo G__ScanCintLN_TObject;
extern G__linked_taginfo G__ScanCintLN_TNamed;
extern G__linked_taginfo G__ScanCintLN_TString;
extern G__linked_taginfo G__ScanCintLN_vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgR;
extern G__linked_taginfo G__ScanCintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__ScanCintLN_string;
extern G__linked_taginfo G__ScanCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ScanCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ScanCintLN_TObjArray;
extern G__linked_taginfo G__ScanCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ScanCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ScanCintLN_TSocket;
extern G__linked_taginfo G__ScanCintLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__ScanCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ScanCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__ScanCintLN_TTree;
extern G__linked_taginfo G__ScanCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__ScanCintLN_TCut;
extern G__linked_taginfo G__ScanCintLN_TArrayF;
extern G__linked_taginfo G__ScanCintLN_EdbAffine2D;
extern G__linked_taginfo G__ScanCintLN_TH1F;
extern G__linked_taginfo G__ScanCintLN_EdbMarksSet;
extern G__linked_taginfo G__ScanCintLN_EdbRun;
extern G__linked_taginfo G__ScanCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__ScanCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__ScanCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__ScanCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__ScanCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__ScanCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__ScanCintLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__ScanCintLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__ScanCintLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__ScanCintLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__ScanCintLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__ScanCintLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__ScanCintLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__ScanCintLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__ScanCintLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__ScanCintLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__ScanCintLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__ScanCintLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__ScanCintLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__ScanCintLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__ScanCintLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__ScanCintLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__ScanCintLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__ScanCintLN_EdbID;
extern G__linked_taginfo G__ScanCintLN_EdbSegP;
extern G__linked_taginfo G__ScanCintLN_EdbTrackP;
extern G__linked_taginfo G__ScanCintLN_EdbPattern;
extern G__linked_taginfo G__ScanCintLN_EdbScanClientBase;
extern G__linked_taginfo G__ScanCintLN_EdbScanClientBasecLcLScanType;
extern G__linked_taginfo G__ScanCintLN_EdbScanClientCommon;
extern G__linked_taginfo G__ScanCintLN_EdbScanClient;
extern G__linked_taginfo G__ScanCintLN_EdbScanClientcLcLScanClientType;
extern G__linked_taginfo G__ScanCintLN_auto_ptrlEEdbScanClientCommongR;
extern G__linked_taginfo G__ScanCintLN_EdbCell2;
extern G__linked_taginfo G__ScanCintLN_EdbLayer;
extern G__linked_taginfo G__ScanCintLN_EdbScanCond;
extern G__linked_taginfo G__ScanCintLN_EdbRunAccess;
extern G__linked_taginfo G__ScanCintLN_EdbMask;
extern G__linked_taginfo G__ScanCintLN_EdbScanSet;
extern G__linked_taginfo G__ScanCintLN_EdbPVRec;
extern G__linked_taginfo G__ScanCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__ScanCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__ScanCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__ScanCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__ScanCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__ScanCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__ScanCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__ScanCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__ScanCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__ScanCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__ScanCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__ScanCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__ScanCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__ScanCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__ScanCintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__ScanCintLN_EdbDataPiece;
extern G__linked_taginfo G__ScanCintLN_EdbPlateP;
extern G__linked_taginfo G__ScanCintLN_TEnv;
extern G__linked_taginfo G__ScanCintLN_EdbScanProc;
extern G__linked_taginfo G__ScanCintLN_EdbProcPars;
extern G__linked_taginfo G__ScanCintLN_EdbTrackFitter;
extern G__linked_taginfo G__ScanCintLN_EdbTrackAssembler;
extern G__linked_taginfo G__ScanCintLN_EdbScanTracking;
extern G__linked_taginfo G__ScanCintLN_MessageManager;
extern G__linked_taginfo G__ScanCintLN_MessageReader;
extern G__linked_taginfo G__ScanCintLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR;
extern G__linked_taginfo G__ScanCintLN_EdbScanClientPav;
extern G__linked_taginfo G__ScanCintLN_EdbScanClientSysal;

/* STUB derived class for protected member access */
