/********************************************************************
* EddCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error EddCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableEddCint();
extern void G__cpp_setup_inheritanceEddCint();
extern void G__cpp_setup_typetableEddCint();
extern void G__cpp_setup_memvarEddCint();
extern void G__cpp_setup_globalEddCint();
extern void G__cpp_setup_memfuncEddCint();
extern void G__cpp_setup_funcEddCint();
extern void G__set_cpp_environmentEddCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "EdbDisplayBase.h"
#include "EdbDisplay.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EddCintLN_TClass;
extern G__linked_taginfo G__EddCintLN_TBuffer;
extern G__linked_taginfo G__EddCintLN_TMemberInspector;
extern G__linked_taginfo G__EddCintLN_TObject;
extern G__linked_taginfo G__EddCintLN_TNamed;
extern G__linked_taginfo G__EddCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EddCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EddCintLN_TList;
extern G__linked_taginfo G__EddCintLN_TObjArray;
extern G__linked_taginfo G__EddCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EddCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EddCintLN_TAttLine;
extern G__linked_taginfo G__EddCintLN_TAttMarker;
extern G__linked_taginfo G__EddCintLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__EddCintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__EddCintLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EddCintLN_TView;
extern G__linked_taginfo G__EddCintLN_TCanvas;
extern G__linked_taginfo G__EddCintLN_TPad;
extern G__linked_taginfo G__EddCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__EddCintLN_TAtt3D;
extern G__linked_taginfo G__EddCintLN_TPolyLine3D;
extern G__linked_taginfo G__EddCintLN_TPolyMarker3D;
extern G__linked_taginfo G__EddCintLN_TArrayF;
extern G__linked_taginfo G__EddCintLN_TArrayI;
extern G__linked_taginfo G__EddCintLN_TButton;
extern G__linked_taginfo G__EddCintLN_TGMainFrame;
extern G__linked_taginfo G__EddCintLN_TText;
extern G__linked_taginfo G__EddCintLN_TPaveText;
extern G__linked_taginfo G__EddCintLN_TArc;
extern G__linked_taginfo G__EddCintLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR;
extern G__linked_taginfo G__EddCintLN_TGeoVolume;
extern G__linked_taginfo G__EddCintLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR;
extern G__linked_taginfo G__EddCintLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EddCintLN_TView3D;
extern G__linked_taginfo G__EddCintLN_Edb3DView;
extern G__linked_taginfo G__EddCintLN_EdbDisplayBase;
extern G__linked_taginfo G__EddCintLN_TGNumberEntry;
extern G__linked_taginfo G__EddCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__EddCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__EddCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__EddCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__EddCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__EddCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__EddCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__EddCintLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__EddCintLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__EddCintLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__EddCintLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__EddCintLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__EddCintLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__EddCintLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__EddCintLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__EddCintLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__EddCintLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__EddCintLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__EddCintLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__EddCintLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__EddCintLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__EddCintLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__EddCintLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__EddCintLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__EddCintLN_EdbSegP;
extern G__linked_taginfo G__EddCintLN_EdbVertex;
extern G__linked_taginfo G__EddCintLN_EdbTrackP;
extern G__linked_taginfo G__EddCintLN_EdbLayer;
extern G__linked_taginfo G__EddCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__EddCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__EddCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__EddCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__EddCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__EddCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__EddCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__EddCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__EddCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__EddCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__EddCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__EddCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__EddCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__EddCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__EddCintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__EddCintLN_listlEVERTEXcLcLRelationmUcOallocatorlEVERTEXcLcLRelationmUgRsPgR;
extern G__linked_taginfo G__EddCintLN_listlEVERTEXcLcLMassCmUcOallocatorlEVERTEXcLcLMassCmUgRsPgR;
extern G__linked_taginfo G__EddCintLN_vectorlEVERTEXcLcLTrackmUcOallocatorlEVERTEXcLcLTrackmUgRsPgR;
extern G__linked_taginfo G__EddCintLN_reverse_iteratorlEvectorlEVERTEXcLcLTrackmUcOallocatorlEVERTEXcLcLTrackmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EddCintLN_EdbVertexRec;
extern G__linked_taginfo G__EddCintLN_EdbSegG;
extern G__linked_taginfo G__EddCintLN_EdbDisplay;
extern G__linked_taginfo G__EddCintLN_EdbVertexG;
extern G__linked_taginfo G__EddCintLN_EdbTrackG;

/* STUB derived class for protected member access */
